<?
/* QM Promisance - Turn-based strategy game
 * Copyright (C) 2001-2008 QMT Productions
 *
 * $URL: https://qmpromisance.svn.sourceforge.net/svnroot/qmpromisance/promisance/tags/release-4_0/lang/ko-KR/common.php $
 * $Id: common.php 1360 2009-01-01 21:27:41Z Quietust $
 */

if (!defined('IN_GAME') && !defined('IN_TURNS'))
	die("Access denied");

$lang['ko-KR'] += array(
	// Past era
	'ERA_PAST_NAME'			=> '과거',
	'ERA_PAST_PEASANTS'		=> '농부',
	'ERA_PAST_FOOD'			=> '곡식',
	'ERA_PAST_RUNES'		=> '마나',
	'ERA_PAST_TRPARM'		=> '보병',
	'ERA_PAST_TRPLND'		=> '투석기',
	'ERA_PAST_TRPFLY'		=> '비행선',
	'ERA_PAST_TRPSEA'		=> '갈레온선',
	'ERA_PAST_TRPWIZ'		=> '마법사',
	'ERA_PAST_BLDPOP'		=> '헛간',
	'ERA_PAST_BLDCASH'		=> '시장',
	'ERA_PAST_BLDTRP'		=> '대장간',
	'ERA_PAST_BLDCOST'		=> '요새',
	'ERA_PAST_BLDWIZ'		=> '마법 타워',
	'ERA_PAST_BLDFOOD'		=> '농장',
	'ERA_PAST_BLDDEF'		=> '방어 타워',
	'ERA_PAST_SPELL_SPY'		=> '수정구',
	'ERA_PAST_SPELL_BLAST'		=> '화염구',
	'ERA_PAST_SPELL_SHIELD'		=> '마법 방패',
	'ERA_PAST_SPELL_STORM'		=> '폭풍',
	'ERA_PAST_SPELL_RUNES'		=> '번개 공격',
	'ERA_PAST_SPELL_STRUCT'		=> '악마의 영혼',
	'ERA_PAST_SPELL_FOOD'		=> '풍요의 뿔',
	'ERA_PAST_SPELL_CASH'		=> '황금의 나무',
	'ERA_PAST_SPELL_GATE'		=> '시간의 문 열기',
	'ERA_PAST_SPELL_UNGATE'		=> '시간의 문 닫기',
	'ERA_PAST_SPELL_FIGHT'		=> '마법 공격',
	'ERA_PAST_SPELL_STEAL'		=> '암흑 도적',
	'ERA_PAST_SPELL_ADVANCE'	=> '미래로 가기',
	'ERA_PAST_SPELL_REGRESS'	=> '과거로 가기',

	// Present era
	'ERA_PRESENT_NAME'		=> '현재',
	'ERA_PRESENT_PEASANTS'		=> '시민',
	'ERA_PRESENT_FOOD'		=> '영양분',
	'ERA_PRESENT_RUNES'		=> '에너지',
	'ERA_PRESENT_TRPARM'		=> '보병대',
	'ERA_PRESENT_TRPLND'		=> '탱크',
	'ERA_PRESENT_TRPFLY'		=> '제트기',
	'ERA_PRESENT_TRPSEA'		=> '전투함',
	'ERA_PRESENT_TRPWIZ'		=> '심령술사',
	'ERA_PRESENT_BLDPOP'		=> '아파트',
	'ERA_PRESENT_BLDCASH'		=> '회사',
	'ERA_PRESENT_BLDTRP'		=> '공장',
	'ERA_PRESENT_BLDCOST'		=> '창고',
	'ERA_PRESENT_BLDWIZ'		=> '초심리 센터',
	'ERA_PRESENT_BLDFOOD'		=> '대규모 농장',
	'ERA_PRESENT_BLDDEF'		=> '벙커',
	'ERA_PRESENT_SPELL_SPY'		=> '관심술',
	'ERA_PRESENT_SPELL_BLAST'	=> '정신 폭격',
	'ERA_PRESENT_SPELL_SHIELD'	=> '정신 방어막',
	'ERA_PRESENT_SPELL_STORM'	=> '폭풍',
	'ERA_PRESENT_SPELL_RUNES'	=> '전뇌 공격',
	'ERA_PRESENT_SPELL_STRUCT'	=> '대천사의 분노',
	'ERA_PRESENT_SPELL_FOOD'	=> '풍요의 뿔',
	'ERA_PRESENT_SPELL_CASH'	=> '황금의 나무',
	'ERA_PRESENT_SPELL_GATE'	=> '시간의 문 열기',
	'ERA_PRESENT_SPELL_UNGATE'	=> '시간의 문 닫기',
	'ERA_PRESENT_SPELL_FIGHT'	=> '마법 공격',
	'ERA_PRESENT_SPELL_STEAL'	=> '보이지 않는 손',
	'ERA_PRESENT_SPELL_ADVANCE'	=> '미래로 가기',
	'ERA_PRESENT_SPELL_REGRESS'	=> '과거로 회귀',

	// Future era
	'ERA_FUTURE_NAME'		=> '미래',
	'ERA_FUTURE_PEASANTS'		=> '일꾼 로봇',
	'ERA_FUTURE_FOOD'		=> '전력 셀',
	'ERA_FUTURE_RUNES'		=> '에네르기',
	'ERA_FUTURE_TRPARM'		=> '사이보그',
	'ERA_FUTURE_TRPLND'		=> '저거너트',
	'ERA_FUTURE_TRPFLY'		=> '호버크래프트',
	'ERA_FUTURE_TRPSEA'		=> '드레드너트',
	'ERA_FUTURE_TRPWIZ'		=> '마음을 꿰뚫는자',
	'ERA_FUTURE_BLDPOP'		=> '길리아드',
	'ERA_FUTURE_BLDCASH'		=> '전자 은행',
	'ERA_FUTURE_BLDTRP'		=> '복제소',
	'ERA_FUTURE_BLDCOST'		=> '초대형 창고',
	'ERA_FUTURE_BLDWIZ'		=> '슈퍼컴퓨터',
	'ERA_FUTURE_BLDFOOD'		=> '대규모 발전소',
	'ERA_FUTURE_BLDDEF'		=> '광선포',
	'ERA_FUTURE_SPELL_SPY'		=> '고위도 위성',
	'ERA_FUTURE_SPELL_BLAST'	=> '이온 폭풍',
	'ERA_FUTURE_SPELL_SHIELD'	=> '플라즈마 방어막',
	'ERA_FUTURE_SPELL_STORM'	=> '폭풍',
	'ERA_FUTURE_SPELL_RUNES'	=> '전자 폭풍',
	'ERA_FUTURE_SPELL_STRUCT'	=> '나노테크 전사',
	'ERA_FUTURE_SPELL_FOOD'		=> '풍요의 프로그램',
	'ERA_FUTURE_SPELL_CASH'		=> '황금의 프로그램',
	'ERA_FUTURE_SPELL_GATE'		=> '시간의 문 실행',
	'ERA_FUTURE_SPELL_UNGATE'	=> '시간의 문 종료',
	'ERA_FUTURE_SPELL_FIGHT'	=> '마법 공격',
	'ERA_FUTURE_SPELL_STEAL'	=> '황금 왜곡',
	'ERA_FUTURE_SPELL_ADVANCE'	=> '미래로 가기',
	'ERA_FUTURE_SPELL_REGRESS'	=> '과거로 회귀',

	'ERA_UNKNOWN'			=> '알려지지 않음',

	// Race names
	'RACE_HUMAN'			=> '인간',
	'RACE_ELF'			=> '엘프',
	'RACE_DWARF'			=> '드워프',
	'RACE_TROLL'			=> '트롤',
	'RACE_GNOME'			=> '놈',
	'RACE_GREMLIN'			=> '그렘린',
	'RACE_ORC'			=> '오크',
	'RACE_DROW'			=> '드로엘프',
	'RACE_GOBLIN'			=> '고블린',
	'RACE_UNKNOWN'			=> '알려지지 않음',

	// Error page titles
	'ERROR_TITLE'			=> '에러',
	'ERROR_TITLE_ACCESS'		=> '접근이 거부되었습니다',

	// Error page messages
	'ERROR_DATABASE_OFFLINE'	=> '데이터베이스에 접근할 수 없습니다. 나중에 다시 방문해주세요.',
	'ERROR_SIGNUP_CLOSED'		=> '죄송합니다. 현재는 새로 가입을 받고 있지 않습니다. 나중에 방문해주세요.',
	'ERROR_NOT_LOGGED_IN'		=> '아직 로그인 하지 않았습니다.!',
	'ERROR_LOGIN_NO_SESSION'	=> '세션 자료가 없습니다!',
	'ERROR_LOGIN_NO_USER'		=> '해당 사용자가 없습니다.',
	'ERROR_LOGIN_OLD_SESSION'	=> '로그인 세션이 만료되었습니다.',
	'ERROR_LOGIN_PAGE_PERMISSION'	=> '이 페이지에 접근할 권한이 없습니다!',
	'ERROR_LOGIN_NO_EMPIRE'		=> '그런 제국은 존재하지 않습니다..',
	'ERROR_LOGIN_EMPIRE_DELETE_MARKED'
					=> '해당 제국은 이미 삭제된것으로 기록되어있습니다.',
	'ERROR_LOGIN_EMPIRE_DELETED'	=> '해당 제국은 이미 삭제되었습니다.',
	'ERROR_LOGIN_EMPIRE_PERMISSION'	=> '해당 제국으로 권한이 없습니다.',
	'ERROR_PLEASE_RELOGIN_CHECK'	=> '사용하시는 웹 브라우저의 설정을 확인하고 다시 <a href="?location=login">로그인</a>해주세요.',
	'ERROR_PLEASE_RELOGIN'		=> '다시 <a href="?location=login">로그인</a>해주세요.',
	'ERROR_LOCK_TIMEOUT'		=> '데이터베이스를 잠그는동안 시간이 경과했습니다. 관리자에게 연락해주세요!',

	// Bans
	'YOU_ARE_BANNED'		=> '당신의 계정은 정지되었습니다.<br />'.
						'날짜: %1$s<br />'.
						'이유: %2$s<br />'.
						'기한: %3$s<br />'.
						'만약 당신 게정이 정지된 이유에 문제가 있다고 생각한다면, 해당 메일(<a href="mailto:%4$s">%4$s</a>)로 게임 관리자에게 연락하세요.<br />'.
						'메일에는 당신의 계정 이름과 제국의 번호를 함께 넣어주세요.<br />',
	'BANNED_NO_REASON'		=> '구체적인 이유 없음',
	'BANNED_PERMANENT'		=> '영구',
	'BANNED_EXPIRES'		=> '%1$s 까지',

	// Security violation
	'SECURITY_TITLE'		=> '보안 문제 발생',
	'SECURITY_DESC'			=> '당신은 게임에 비정상적인 방법으로 접근하였거나, 오류가 발생하였습니다.',
	'SECURITY_BADPAGE'		=> '당신은 게임에 <strong>존재하지 않는 페이지</strong>(%1$s)에 접근하였습니다.',
	'SECURITY_BADREF'		=> '당신은 게임 내부(%3$s)가 아닌 외부(%2$s)에서 해당 페이지(%1$s)에 접근하였습니다.',
	'SECURITY_NOREF'		=> '당신은 <strong>즐겨찾기</strong>를 통해서 접속하였거나 <strong>내부 주소를 복사</strong>해서 접근하였습니다.',
	'SECURITY_UNKNOWN'		=> '당신이 방문하려고 했던 페이지 <b>%1$s</b> 에서 알 수 없는 오류 <b>%2$s</b> 가 발생하였습니다.',
	'SECURITY_INSTRUCT'		=> '만약 이 오류가 계속 해서 발생한다면, 아래의 방법대로 해보세요.<br />'.
						'1) 첫 페이지 <a href="%1$s">%1$s</a>로 돌아가서 다시 로그인하세요.<br />'.
						'2) 웹 프라우저를 최신 버전으로 바꾸세요.<br />'.
						'3) 현재 사용중인 프록시 설정을 밖거나 없에세요.<br />'.
						'4) 게임 관리자의 연락처 <a href="mailto:%2$s">%2$s</a>로 연락주세요.<br />'.
						'5) 모든 방법이 효과가 없다면 인터넷 공급자에게 문의하세요.',

	// Round status
	'ROUND_WILL_BEGIN'		=> '이번 판은 %1$s 에 시작합니다...',
	'ROUND_WILL_BEGIN_FORMAT'	=> 'Y년 n월 j일 A h:i:s',
	'ROUND_WILL_END'		=> '이번 판은 %1$s 에 종료됩니다...',
	'ROUND_WILL_END_FORMAT'		=> 'Y년 n월 j일 A h:i:s',
	'ROUND_HAS_ENDED'		=> '이번 판은 종료되었습니다. 다음 판을 기대해주세요!',

	// Input error messages
	'INPUT_NEED_USERNAME'		=> '사용자 입력을 입력해주세요!',
	'INPUT_USERNAME_TOO_LONG'	=> '사용자 이름이 너무 짧습니다!',
	'INPUT_NEED_PASSWORD'		=> '비밀번호를 입력해주세요!',
	'INPUT_NEED_NICKNAME'		=> '별명을 입력해주세요!',
	'INPUT_NICKNAME_TOO_LONG'	=> '별명이 너무 깁니다!',
	'INPUT_NEED_EMAIL'		=> '정상적인 E-Mail주소를 입력해주세요.',
	'INPUT_EMAIL_TOO_LONG'		=> 'E-mail 주소가 너무 깁니다!',
	'INPUT_PASSWORD_MISMATCH'	=> '입력한 비밀번호가 서로 다릅니다!',
	'INPUT_EMAIL_MISMATCH'		=> '입력한 이메일이 서로 다릅니다!',
	'INPUT_NEED_EMPIRE'		=> '제국명을 입력해야됩니다!',
	'INPUT_EMPIRE_TOO_LONG'		=> '제국명이 너무 깁니다!',
	'INPUT_USERNAME_IN_USE'		=> '해당 사용자명은 이미 사용중입니다!',
	'INPUT_EMAIL_IN_USE'		=> '해당 E-Mail주소는 이미 사용중입니다!',
	'INPUT_EMPIRE_IN_USE'		=> '죄송하지만 해당 제국명은 이미 사용중입니다!',
	'INPUT_INCORRECT_PASSWORD'	=> '잘못된 비밀번호를 입력하였습니다!',
	'INPUT_EMPIRE_ID'		=> '잘못된 제국 번호를 입력하였습니다!',
	'INPUT_SPELL_NAME'		=> '사용할 마법 기술을 선택해야됩니다!',
	'INPUT_USERNAME_INVALID'	=> '해당 사용자명은 사용할 수 없습니다!',
	'INPUT_NICKNAME_INVALID'	=> '해당 별명은 사용할 수 없습니다!',
	'INPUT_EMPIRE_INVALID'		=> '해당 제국명은 사용할 수 없습니다!',

	// Input labels (with trailing colons), mostly
	'LABEL_USERNAME'		=> '계정:',
	'LABEL_PASSWORD'		=> '비밀번호:',
	'LABEL_PASSWORD_NEW'		=> '새 비밀번호:',
	'LABEL_PASSWORD_VERIFY'		=> '비밀번호 확인:',
	'LABEL_NICKNAME'		=> '별명:',
	'LABEL_EMAIL'			=> 'E-Mail:',
	'LABEL_EMAIL_VERIFY'		=> 'E-Mail 확인:',
	'LABEL_EMPIRE'			=> '제국 이름:',
	'LABEL_RACE'			=> '종족:',
	'LABEL_ROUND_START'		=> '판이 시작한 날짜:',
	'LABEL_ROUND_COOLDOWN'		=> '판이 쉬는 시간:',
	'LABEL_ROUND_END'		=> '판이 끝나는 날짜:',
	'LABEL_CLAN'			=> '클랜:',
	'LABEL_CLAN_NAME'		=> '클랜 이름:',
	'LABEL_CLAN_NEWS'		=> '클랜 소식:',
	'LABEL_EMPIRE_RECIPIENT'	=> '보내는 제국:',
	'LABEL_EMPIRE_TARGET'		=> '받는 제국:',
	'LABEL_VALCODE'			=> '인증 번호:',
	'LABEL_FROM'			=> 'From:',
	'LABEL_TO'			=> 'To:',
	'LABEL_DATE'			=> '날짜:',
	'LABEL_SUBJECT'			=> '제목:',

	// Row labels
	'ROW_CASH'			=> '돈',
	'ROW_TURNS'			=> '턴',
	'ROW_TURNSUSED'			=> '사용한 턴',
	'ROW_STOREDTURNS'		=> '남겨둔 턴',
	'ROW_LAND'			=> '땅',
	'ROW_RANK'			=> '등수',
	'ROW_LANDACRES'			=> '땅 평수',
	'ROW_NETWORTH'			=> '총 가치',
	'ROW_HEALTH'			=> '건강',
	'ROW_TAX'			=> '세율',
	'ROW_RACE'			=> '종족',
	'ROW_ERA'			=> '시대',
	'ROW_POPULATION'		=> '인구',

	// Column labels
	'COLUMN_UNIT'			=> '유닛',
	'COLUMN_STRUCTURE'		=> '건축물',
	'COLUMN_OWNED'			=> '소유함',
	'COLUMN_AVAIL'			=> '가능한',
	'COLUMN_PRICE'			=> '가격',
	'COLUMN_QUANTITY'		=> '양',
	'COLUMN_STATUS'			=> '상태',
	'COLUMN_CANSEND'		=> '보낼수 있음',
	'COLUMN_SEND'			=> '보내기',
	'COLUMN_CANBUILD'		=> '건설 가능',
	'COLUMN_BUILD'			=> '건설',
	'COLUMN_CANDEMO'		=> '파괴 가능',
	'COLUMN_DEMO'			=> '파괴하기',
	'COLUMN_CANDROP'		=> '버릴 수 있음',
	'COLUMN_DROP'			=> '버리기',
	'COLUMN_CANBUY'			=> '구입 가능',
	'COLUMN_BUY'			=> '구입',
	'COLUMN_CANSELL'		=> '팔 수 있음',
	'COLUMN_SELL'			=> '팔기',
	'COLUMN_CLANRANK'		=> '클랜 등급',
	'COLUMN_EMPIRE'			=> '제국',
	'COLUMN_NETWORTH'		=> '총 가치',
	'COLUMN_RANK'			=> '등급',
	'COLUMN_RACE'			=> '종족',
	'COLUMN_ERA'			=> '시대',
	'COLUMN_LAND'			=> '땅',
	'COLUMN_CLAN'			=> '클랜',
	'COLUMN_SCORE'			=> '점수',
	'COLUMN_SHARING'		=> '공유',
	'COLUMN_SHAREYOU'		=> '당신이 공유한',
	'COLUMN_SHARETOTAL'		=> '모두에게 공유',
	'COLUMN_CLAN_NAME'		=> '이름',
	'COLUMN_CLAN_TITLE'		=> '제목',
	'COLUMN_CLAN_MEMBERS'		=> '소속국가',
	'COLUMN_CLAN_AVGNET'		=> '평균 자산',
	'COLUMN_CLAN_TOTALNET'		=> '총 자산',
	'COLUMN_CLAN_LEADER'		=> '회장',
	'COLUMN_CLAN_ASST'		=> '부장',
	'COLUMN_CLAN_FAS'		=> '외교부 장관',
	'COLUMN_DEATH'			=> '사망',
	'COLUMN_ATTACKS'		=> '공격',
	'COLUMN_DEFENDS'		=> '방어',
	'COLUMN_KILLS'			=> '죽인 수',
	'COLUMN_DEATHS'			=> '죽음',
	'COLUMN_USER'			=> '플레이어',
	'COLUMN_AVGRANK'		=> '평균 등수',
	'COLUMN_BESTRANK'		=> '최고 등ㅅ',
	'COLUMN_ROUNDSPLAYED'		=> '참여판 판',

	'COLUMN_ADMIN_USERID'		=> 'UID',
	'COLUMN_ADMIN_EMPIREID'		=> 'EID',
	'COLUMN_ADMIN_NICKNAME'		=> '별명',
	'COLUMN_ADMIN_USERNAME'		=> '사용자 이름',
	'COLUMN_ADMIN_EMPNAME'		=> '이름',
	'COLUMN_ADMIN_IPADDR'		=> 'IP',
	'COLUMN_ADMIN_IDLE'		=> '휴식',
	'COLUMN_ADMIN_EMAIL'		=> 'E-mail',
	'COLUMN_ADMIN_FLAGS'		=> 'Flags',
	'COLUMN_ADMIN_COMMENT'		=> '설명',

	// Common singular/plural labels
	'DAYS_SINGLE'			=> '%s 일',
	'DAYS_PLURAL'			=> '%s 일',
	'HOURS_SINGLE'			=> '%s 시간',
	'HOURS_PLURAL'			=> '%s 시간',
	'MINUTES_SINGLE'		=> '%s 분',
	'MINUTES_PLURAL'		=> '%s 분',
	'TURNS_SINGLE'			=> '%s 턴',
	'TURNS_PLURAL'			=> '%s 턴',
	'OLD_MESSAGES_SINGLE'		=> '%s개의 메시지',
	'OLD_MESSAGES_PLURAL'		=> '%s개의 메시지',
	'NEW_MESSAGES_SINGLE'		=> '%s개의 새 메시지',
	'NEW_MESSAGES_PLURAL'		=> '%s개의 새 메시지',
	'SHIPMENTS_SINGLE'		=> '%s척의 배',
	'SHIPMENTS_PLURAL'		=> '%s척의 배',
	'STRUCTURES_SINGLE'		=> '%s개의 구조물',
	'STRUCTURES_PLURAL'		=> '%s개의 구조물',
	'ACRES_SINGLE'			=> '%s평 땅',
	'ACRES_PLURAL'			=> '%s평 땅',
	'TICKETS_SINGLE'		=> '%s개 티켓',
	'TICKETS_PLURAL'		=> '%s개 티켓',
	'EMPIRES_SINGLE'		=> '%s개의 제국',
	'EMPIRES_PLURAL'		=> '%s개의 제국',

	// Common shared strings
	'TURNS_UNAVAILABLE_START'	=> '이번 회 게임이 시작하기 전에 턴을 시작할 수 없습니다.',
	'TURNS_UNAVAILABLE_END'		=> '이번 회 게임이 종료되어 턴을 더 사용할 수 없습니다.',
	'COMMON_YES'			=> '예',
	'COMMON_NO'			=> '아니요',
	'COMMON_YES_SHORT'		=> 'Y',
	'COMMON_NO_SHORT'		=> 'N',
	'COMMON_COLORKEY'		=> '색깔 값:',
	'COMMON_COLOR_NEW'		=> '초보',
	'COMMON_COLOR_DISABLED'		=> '불가',
	'COMMON_COLOR_ADMIN'		=> '영자',
	'COMMON_COLOR_PROTECT'		=> '보호됨',
	'COMMON_COLOR_DEAD'		=> '사망',
	'COMMON_POINTS_GAIN_SINGLE'	=> '(+%spt)',
	'COMMON_POINTS_GAIN_PLURAL'	=> '(+%spts)',
	'COMMON_POINTS_LOSE_SINGLE'	=> '(-%spt)',
	'COMMON_POINTS_LOSE_PLURAL'	=> '(-%spts)',
	'COMMON_USER_NAMEID'		=> '%1$s (%2$s)',
	'COMMON_EMPIRE_NAMEID'		=> '%1$s (%2$s)',
	'COMMON_CLAN_NAMEID'		=> '%1$s (%2$s)',
	'COMMON_USER_UNINITIALIZED'	=> '초기회 되지 않은 사용자',
	'COMMON_EMPIRE_UNINITIALIZED'	=> '초기화 되지 않은 제국',
	'COMMON_CLAN_UNINITIALIZED'	=> '초기화 되지 않은 클랜',
	'COMMON_PAGES_LABEL'		=> '페이지:',
	'COMMON_PAGES_PREV'		=> '&lt;',
	'COMMON_PAGES_NEXT'		=> '&gt;',
	'COMMON_PAGES_SEP'		=> ', ',
	'COMMON_PAGES_GAP'		=> ' ... ',
	'COMMON_TURNS_SUMMARY'		=> '요약해서 보여주기',
	'COMMON_TURNS_CURRENT_MAX'	=> '%1$s (최대 %2$s)',

	'ADMIN_STATUS_DELETED'		=> '삭제된',
	'ADMIN_STATUS_ADMIN'		=> '운영자',
	'ADMIN_STATUS_MODERATOR'	=> '조정자',
	'ADMIN_STATUS_DISABLED_MULTI'	=> '알 수 없음 (multi:%1$s)',
	'ADMIN_STATUS_DISABLED_OTHER'	=> '알 수 없음 (other:%1$s)',
	'ADMIN_STATUS_UNVALIDATED_NOTIFY'	=> 'Unvalidated (notify)',
	'ADMIN_STATUS_DEAD_NOTIFY'	=> 'Dead (notify)',
	'ADMIN_STATUS_VACATION'		=> '휴가',
	'ADMIN_STATUS_UNKNOWN_NOTIFY'	=> '알 수 없음 (notify)',
	'ADMIN_STATUS_DEAD'		=> '사망',
	'ADMIN_STATUS_MULTI'		=> '다중',
	'ADMIN_STATUS_NORMAL'		=> '일반',
	'ADMIN_STATUS_UNVALIDATED'	=> '인증되지 않음',
	'ADMIN_STATUS_NEW'		=> '새 계정',

	// includes/header
	'HEADER_LOGGED_IN_AS'		=> '현재 <span style="font-size:large">%1$s</span>,<span style="font-size:large">%2$s</span>제국 으로 로그인하였습니다.',
	'HEADER_GAME_NEWS'		=> '<b>게임 소식:</b>',
	'HEADER_GUIDE'			=> '[게임 설명]',
	'HEADER_REFRESH'		=> '[새로 고침]',

	'VACATION_NOT_LOCKED'		=> '이 계정은 %1$s전 부터 휴가 상태입니다.<br />%2$s 지나고 나면 제국이 보호받게 됩니다.<br />',
	'VACATION_LOCKED'		=> '이 계정은 %1$s 동안 휴가 상태이며 제국은 보호받고있습니다.<br />',
	'VACATION_CANNOT_UNLOCK'	=> '%1$s 이후에 휴가를 끝낼 수 있습니다.<br />',
	'VACATION_CAN_UNLOCK'		=> '원하실 때 바로 휴가를 끝내고 돌아올 수 있습니다.<br />',
	'VACATION_UNLOCK_SUBMIT'	=> '휴가 끝내기',

	'DEAD_UNNOTIFIED'		=> '당신이 도착했을때는, 남아있는것은 폐허 뿐입니다. 찢겨져 버린 편지 조각만이 무슨 일이었는지 말해 줄 뿐입니다...',
	'DEAD_NOTIFIED'			=> '당신의 제국은 파괴되었습니다. 무슨 일로 파괴 당했는지 확인 해 보는것 말고는 할 수 있는것이 없습니다...',
	'DEAD_DELETE_NOTICE'		=> '당신의 제국은 %1$s 수에 파괴됩니다. 그러고 난 다음에는 새로운 제국을 만드실 수 있습니다.',

	'UNVALIDATED_UNNOTIFIED'	=> '이제 인증 코드가 필요합니다. E-Mail에 인증 코드가 도착하지 않았다면, 다시 요청하실 수 있습니다.',
	'UNVALIDATED_NOTIFIED'		=> '더 진행하기 위해서는 인증 코드를 입력해야됩니다. E-Mail에 인증 코드가 도착하지 않았다면, 다시 받으실 수 있습니다.',
	'UNVALIDATED_ENTER_CODE'	=> '인증 코드를 입력하세요:',

	'DISABLED_DEFAULT_REASON'	=> '일반적인 이유',
	'DISABLED_DEFAULT_REASON_MULTI'	=> '다중 계정 사용',
	'DISABLED_BY_ADMIN'		=> '이 계정은 %2$s 때문에 %1$s에 의해 사용이 정지되었습니다.<br />계속 게임을 하고싶다면 관리자에게 메일<a href="mailto:%3$s?subject=%4$s">%3$s</a>을 보내보세요.<br />',
	'DISABLED_BY_SCRIPT'		=> '이 계정은 %1$s에 의해서 자동으로 정지되었습니다.<br />게임을 다시 하고싶다면 관리자에게 메일<a href="mailto:%2$s?subject=%3$s">%2$s</a> 보내세요.<br />',
	'DISABLED_EMAIL_SUBJECT'	=> '%1$s - 정지된 %2$s',
	'DISABLED_EMAIL_REMINDER'	=> '당신의 제국 이름과 번호, 그리고 게임 이름(%1$s)을 제목에 쓰지 않으면 처리되지 않을 수 있습니다.<br />',

	'HEADER_EMPIRE_DELETED'		=> '당신의 제국은 삭제되었습니다. 지금까지 게임을 즐겨주셔서 감사합니다!',

	// includes/guide
	'GUIDE_HEADER'			=> '화생공 연대기 설명',
	'GUIDE_INTRO'			=> '시작하기',
	'GUIDE_INFO'			=> '정보',
	'GUIDE_TURNS'			=> '턴 사용하기',
	'GUIDE_FINANCE'			=> '돈 관련',
	'GUIDE_FOREIGN'			=> '대외 관계',
	'GUIDE_MANAGE'			=> '관리',
	'GUIDE_ADMIN'			=> '운영',
	'GUIDE_SELECT_TOPIC'		=> '주제를 선택하세요:',

	// includes/magic
	'SPELL_GENERIC_SUCCESS'		=> '당신이 사용한 주술이 <span class="cgood">성공</span>했습니다!',
	'SPELL_GENERIC_FAILED'		=> '당신은 주술을 사용하였지만 <span class="cbad">실패</span>하였습니다!',
	'SPELL_GENERIC_FAILED_LOSSES'	=> '주술이 잘못되어 %1$s %2$s들이 사망했습니다!',
	'SPELL_GENERIC_SHIELDED'	=> '당신이 사용한 주술이 <span class="cbad">성공</span>했지만 <span class="cwarn">일부 막혔</span>습니다.',

	// spells/*
	'SPELL_SPY_SUCCESS'		=> '이러한 정보를 얻어왔습니다:',
	'SPELL_BLAST_SUCCESS'		=> '적의 병력의 3%를 날려버렸습니다!',
	'SPELL_BLAST_SHIELDED'		=> '적의 병력의 1%를 날려버렸습니다.',
	'SPELL_SHIELD_CREATE'		=> '앞으로 12시간동안 마법 방어막이 작동합니다!',
	'SPELL_SHIELD_EXTEND'		=> '마법 방어막을 3시간 연장하였습니다!',
	'SPELL_SHIELD_RENEW'		=> '마법 방어막이 12시간으로 늘었습니다!',
	'SPELL_STORM_SUCCESS'		=> '폭풍으로 %1$s %2$s와(과) %3$s을(를) 날려버렸습니다!',
	'SPELL_STORM_SHIELDED'		=> '폭풍으로 %1$s %2$s와(과) %3$s을(를) 날려버렸습니다.',
	'SPELL_RUNES_SUCCESS'		=> '%1$s개의 적군 %2$s을(를) 파괴하였습니다!',
	'SPELL_RUNES_SHIELDED'		=> '%1$s개의 적군 %2$s을(를) 파괴하였습니다.',
	'SPELL_STRUCT_SUCCESS'		=> '적국의 %1$s개의 건축물을 파괴했습니다!',
	'SPELL_STRUCT_SHIELDED'		=> '적국의 %1$s개의 건축물을 파괴했습니다!',
	'SPELL_STRUCT_NOEFFECT'		=> '아쉽게도, 주술이 아무런 효과가 없었습니다.',
	'SPELL_FOOD_SUCCESS'		=> '당신의 곡식 창고에 %2$s %1$s개가 쌓였습니다!',
	'SPELL_CASH_SUCCESS'		=> '당신의 금고에 %1$s이 쌓였습니다!',
	'SPELL_GATE_CREATE'		=> '이제 시간의 문이 열렸습니다. 앞으로 12시간동안 어떠한 제국과도 교류할 수 있습니다!',
	'SPELL_GATE_EXTEND'		=> '시간의 문이 3시간 연장되었습니다!',
	'SPELL_GATE_RENEW'		=> '시간의 문이 다시 12시간으로 늘었습니다!',
	'SPELL_UNGATE_SUCCESS'		=> '시간의 문이 정상적으로 닫혔습니다!',
	'SPELL_FIGHT_ATTACKING'		=> '당신의 %1$s이(가) %2$s 의 %3$s 으로 정신을 집중하고 있습니다...',
	'SPELL_FIGHT_SUCCESS_HEADER'	=> '%1$s의 땅에 강력한 기운이 감돌면서 당신의 %2$s으로 %3$s평의 땅을 빼앗았습니다!',
	'SPELL_FIGHT_SUCCESS_LOSSES'	=> '%3$s of your opponent\'s %4$s are eliminated in the resulting shockwave, but not before destroying %1$s of your %2$s.',
	'SPELL_FIGHT_BLOCKED_HEADER'	=> 'A massive field of energy begins to form over the lands of %1$s, but their %2$s reflect it back upon you!',
	'SPELL_FIGHT_BLOCKED_LOSSES'	=> 'The resulting shockwave eliminates %1$s of your %2$s, while %3$s of your opponent\'s %4$s are destroyed from the initial energy field.',
	'SPELL_STEAL_SUCCESS'		=> '적국의 창고에서 %1$s을 약탈하였습니다!',
	'SPELL_STEAL_SHIELDED'		=> '적국의 창고에서 %1$s을 약탈하였습니다.',
	'SPELL_ADVANCE_SUCCESS'		=> '다음 세대로 넘어왔습니다!',
	'SPELL_REGRESS_SUCCESS'		=> '이전 세대로 돌아왔습니다!',

	// turns output
	'TURNS_CASH_HEADER'		=> '경제 상태',
	'TURNS_CASH_INCOME'		=> '수입:',
	'TURNS_CASH_EXPENSE'		=> '지출:',
	'TURNS_CASH_WARTAX'		=> '전쟁세:',
	'TURNS_CASH_LOANPAY'		=> '대출이자 지출:',
	'TURNS_CASH_NET'		=> '총 합:',
	'TURNS_FOOD_HEADER'		=> '농사 상태',
	'TURNS_FOOD_PRODUCE'		=> '생산량:',
	'TURNS_FOOD_CONSUME'		=> '소비량:',
	'TURNS_FOOD_NET'		=> '총 합:',
	'TURNS_UNITS_HEADER'		=> '인구 &amp; 군사 상태',
	'TURNS_UNITS_NOCHANGE'		=> '변화 없음',
	'TURNS_TAX_HIGH'		=> '당신 제국의 시민들은 높은 세금에 분노하고있습니다.',
	'TURNS_TAX_LOW'			=> '낮은 세금 때문에 당신의 제국으로 이주하는 사람들이 생기고 있습니다.',
	'TURNS_TROUBLE_CASH'		=> '당신의 제국을 유지하는데 자금이 많이 부족합니다! 세계 은행으로 가서 대출을 받으세요...러쉬엔케쉬...',
	'TURNS_TROUBLE_LOAN'		=> '당신이 곤란에 빠졌지만, 세계 은행은 대출을 거부했습니다!',
	'TURNS_TROUBLE_FOOD'		=> '식량이 부족합니다! 지금 사람들이 굶고 있습니다!',
	'TURNS_TROUBLE_LOSSES_CONTINUE'	=> '%1$s of your population and military have deserted your empire! Unfortunately, you have no choice but to continue...',
	'TURNS_TROUBLE_LOSSES_HALT'	=> '%1$s of your population and military have deserted your empire! You immediately stop what you are doing, preventing the problem from getting any worse.',

	// empire news reports
	'EMPNEWS_DATE_FORMAT'		=> '%1$s 전',
	'EMPNEWS_GIVE_MARKET_SELL'	=> '%2$s %1$s개를 시장에 팔았습니다.',
	'EMPNEWS_GIVE_LOTTERY'		=> '복권에 당첨되었습니다!',
	'EMPNEWS_GIVE_MARKET_RETURN'	=> '%2$s %1$s개는 결국 시장에서 팔지 못했습니다.',
	'EMPNEWS_GIVE_AID_SEND'		=> '%1$s의 %2$s이(가) 지원을 보냈고 %3$s이(가) 고국으로 귀환했습니다.',
	'EMPNEWS_GIVE_AID_RETURN_ALL'	=> '당신의 %1$s 지원이 전부 돌아왔습니다.',
	'EMPNEWS_GIVE_AID_RETURN_SOME'	=> '%1$s 중 %2$s %3$s이(가) 돌아왔습니다.',
	'EMPNEWS_GIVE_COLUMN_DATE'	=> '날짜',
	'EMPNEWS_GIVE_COLUMN_GAIN'	=> '이득',
	'EMPNEWS_GIVE_COLUMN_DESCRIBE'	=> '설명',
	'EMPNEWS_ATTACH_MARKET_SELL'	=> '%2$s %1$s개를 %3$s에 팔았습니다.',
	'EMPNEWS_ATTACH_LOTTERY'	=> '오늘 복권 당첨 번호가 발표되었습니다. %1$s에 당첨되었습니다!',
	'EMPNEWS_ATTACH_MARKET_RETURN'	=> '%2$s %1$s개가 시장에서 %3$s에 판매되지 못하고 %4$s개만 돌아왔습니다.',
	'EMPNEWS_ATTACH_AID_SEND'	=> '%1$s has sent you %2$s %3$s carrying:',
	'EMPNEWS_ATTACH_AID_RETURN_ALL'		=> 'Your %1$s %2$s have returned from their aid shipment to %3$s.',
	'EMPNEWS_ATTACH_AID_RETURN_SOME'	=> '%1$s of your %2$s %3$s have returned from their aid shipment to %4$s.',
	'EMPNEWS_ATTACH_AID_RETURN_NONE'	=> 'None of your %1$s %2$s made it back intact from their aid shipment to %3$s.',
	'EMPNEWS_MAGIC_SPY_FAILED'	=> '%1$s제국이 당신의 제국을 염탐하려고 하다가 걸렸습니다!',
	'EMPNEWS_MAGIC_SPY_SUCCESS'	=> '다른 제국이 당신을 염탐하였습니다!',
	'EMPNEWS_MAGIC_BLAST_FAILED'	=> '%1$s제국이 당신의 병력을 날려 보내려고 하다가 걸렸습니다!',
	'EMPNEWS_MAGIC_BLAST_SUCCESS'	=> '당신의 병력 중 3%%가 %1$s제국에 의해 날라갔습니다!',
	'EMPNEWS_MAGIC_BLAST_SHIELDED'	=> '당신의 병력 중 1%%가 %1$s제국에 의해 날라갔습니다!',
	'EMPNEWS_MAGIC_STORM_FAILED'	=> '%1$s제국이 당신의 제국에 폭풍을 이르키려고 하다가 걸렸습니다!',
	'EMPNEWS_MAGIC_STORM_SUCCESS'	=> '폭풍이 %1$s %2$s 와(과) %3$s을(를) 날려보냈습니다!',
	'EMPNEWS_MAGIC_STORM_SHIELDED'	=> '마법 방어막이 방어하여서 폭풍으로 %1$s %2$s 와(과) %3$s만큼만 날라갔습니다',
	'EMPNEWS_MAGIC_RUNES_FAILED'	=> '%1$s제국이 당신의 %2$s을(를) 어지럽히려고 하다가 발각되었습니다!',
	'EMPNEWS_MAGIC_RUNES_SUCCESS'	=> '번개가 %1$s개의 %2$s을(를) 파괴하였습니다!',
	'EMPNEWS_MAGIC_RUNES_SHIELDED'	=> '마법 방어막이 방어하여서 번개로 %1$s개의 %2$s만큼만 파괴되었습니다.',
	'EMPNEWS_MAGIC_STRUCT_FAILED'	=> '%1$s제국이 당신에게 괴물을 보내려고 하다가 하다가 발각되었습니다!',
	'EMPNEWS_MAGIC_STRUCT_SUCCESS'	=> '당신의 제국에서 괴물들이 건물을 파괴하였습니다!',
	'EMPNEWS_MAGIC_STRUCT_SHIELDED'	=> '당신의 제국에서 괴물들이 건물을 파괴하였지만 마법 방어막으로 많이 막았습니다.',
	'EMPNEWS_MAGIC_STRUCT_NOEFFECT'	=> 'Monsters were sent into your empire, but they found nothing to destroy.',
	'EMPNEWS_MAGIC_FIGHT_FAILED'	=> 'You find %1$s attempting to fight with your %2$s!',
	'EMPNEWS_MAGIC_FIGHT_SUCCESS'	=> '%1$s 제국이 %2$s으로(로) 공격했습니다!',
	'EMPNEWS_MAGIC_FIGHT_DEFEATED'	=> '%1$s평 땅을 빼았겼습니다.',
	'EMPNEWS_MAGIC_FIGHT_DEFENDED'	=> '공격을 막아냈습니다.',
	'EMPNEWS_MAGIC_FIGHT_LOSSES_YOU'	=> '전쟁 중에 %1$s개의 %2$s을(를) 잃었습니다.',
	'EMPNEWS_MAGIC_FIGHT_LOSSES_ENEMY'	=> '방어하면서 적군의 %2$s을(를) %1$s개 파괴하였습니다.',
	'EMPNEWS_MAGIC_STEAL_FAILED'	=> 'You find %1$s trying to embezzle your money!',
	'EMPNEWS_MAGIC_STEAL_SUCCESS'	=> '누군가가 당신의 금고에서 %1$s을 가져갔습니다!',
	'EMPNEWS_MAGIC_STEAL_SHIELDED'	=> '누군가가 당시의 금고에서 %1$s을 가져갔지만 방어막이 없었다면 피해가 더 컸을것입니다.',
	'EMPNEWS_MILITARY_AID'		=> 'Your forces came to the aid of %1$s in defense from %2$s!',
	'EMPNEWS_MILITARY_KILL'		=> 'As %1$s delivers their final blow, your empire collapses...',
	'EMPNEWS_MILITARY_STANDARD'	=> '%1$s제국이 공격하였습니다!',
	'EMPNEWS_MILITARY_SURPRISE'	=> '%1$s제국이 급습하였습니다!',
	'EMPNEWS_MILITARY_UNIT'		=> '%1$s제국이 %2$s을(를) 이용해 공격하였습니다!',
	'EMPNEWS_MILITARY_DEFEATED'	=> '적국이 %1$s평을 점령하였습니다.',
	'EMPNEWS_MILITARY_DEFENDED'	=> '방어선을 유지하면서 공격을 막았습니다.',
	'EMPNEWS_MILITARY_LOSSES_YOU_SINGLE'		=> '공격 받는 동안, %1$s개의 %2$s의 손실을 입었습니다.',
	'EMPNEWS_MILITARY_LOSSES_YOU_MULTIPLE'		=> '공격 받는 동안, %1$s들이 파괴되었습니다.',
	'EMPNEWS_MILITARY_LOSSES_ENEMY_SINGLE'		=> '방어 하는 동안, %1$s개의 %2$s을(를) 파괴하였습니다..',
	'EMPNEWS_MILITARY_LOSSES_ENEMY_MULTIPLE'	=> '방어 하는 동안, %1$s들을 파괴하였습니다.',
	'EMPNEWS_CLAN_CREATE'		=> 'You founded <b>%1$s</b>.',
	'EMPNEWS_CLAN_DISBAND'		=> 'You disbanded <b>%1$s</b>.',
	'EMPNEWS_CLAN_JOIN_SELF'	=> 'You joined <b>%1$s</b>.',
	'EMPNEWS_CLAN_JOIN_OTHER'	=> '%1$s joined <b>%2$s</b>.',
	'EMPNEWS_CLAN_LEAVE_SELF'	=> 'You left <b>%1$s</b>.',
	'EMPNEWS_CLAN_LEAVE_OTHER'	=> '%1$s left <b>%2$s</b>.',
	'EMPNEWS_CLAN_REMOVE'		=> '%1$s removed you from <b>%2$s</b>.',
	'EMPNEWS_CLAN_GRANT_LEADER'	=> '%1$s made you leader of <b>%2$s</b>.',
	'EMPNEWS_CLAN_INHERIT_LEADER'	=> 'You inherited leadership of <b>%1$s</b> from the late %2$s.',
	'EMPNEWS_CLAN_REVOKE_LEADER'	=> '%1$s has removed you from your position as Leader of <b>%2$s</b>.',
	'EMPNEWS_CLAN_GRANT_ASSISTANT'	=> '%1$s made you Assistant Leader of <b>%2$s</b>.',
	'EMPNEWS_CLAN_REVOKE_ASSISTANT'	=> '%1$s has removed you from your position as Assistant Leader of <b>%2$s</b>.',
	'EMPNEWS_CLAN_GRANT_MINISTER'	=> '%1$s made you a Minister of Foreign Affairs of <b>%2$s</b>.',
	'EMPNEWS_CLAN_REVOKE_MINISTER'	=> '%1$s has removed you from your position as Minister of Foreign Affairs of <b>%2$s</b>.',
	'EMPNEWS_CLAN_WAR_START'	=> 'By the command of %1$s, <b>%2$s</b> has declared war on <b>%3$s</b>!',
	'EMPNEWS_CLAN_WAR_REQUEST'	=> '%1$s steps forward in apology and pledges to resolve <b>%2$s</b>\'s conflict with <b>%3$s</b>!',
	'EMPNEWS_CLAN_WAR_STOP'		=> '%1$s, on the behalf of <b>%2$s</b>, accepts <b>%3$s</b>\'s declaration of peace.',
	'EMPNEWS_CLAN_WAR_RETRACT'	=> '%1$s recants <b>%2$s</b>\'s declaration of peace with <b>%3$s</b> and continues the war!',
	'EMPNEWS_CLAN_WAR_REJECT'	=> '%1$s, representing <b>%2$s</b>, rejects <b>%3$s</b>\'s declaration of peace and continues the war!',
	'EMPNEWS_CLAN_WAR_GONE'		=> '<b>%1$s</b>, whom <b>%2$s</b> was at war with, has been disbanded.',
	'EMPNEWS_CLAN_ALLY_REQUEST'	=> 'By the request of %1$s, <b>%2$s</b> reaches out its arms toward <b>%3$s</b> in alliance!',
	'EMPNEWS_CLAN_ALLY_START'	=> 'By the authority of %1$s, <b>%2$s</b> accepts and establishes an alliance with <b>%3$s</b>!',
	'EMPNEWS_CLAN_ALLY_STOP'	=> 'By %1$s\'s order, <b>%2$s</b> ceases all diplomatic relations with <b>%3$s</b>!',
	'EMPNEWS_CLAN_ALLY_RETRACT'	=> '%1$s retracts <b>%2$s</b>\'s request for alliance with <b>%3$s</b>!',
	'EMPNEWS_CLAN_ALLY_DECLINE'	=> '%1$s, on the behalf of <b>%2$s</b>, declines <b>%3$s</b>\'s request for an alliance!',
	'EMPNEWS_CLAN_ALLY_GONE'	=> '<b>%1$s</b>, an ally of <b>%2$s</b>, has been disbanded.',
	'EMPNEWS_COLUMN_TIME'		=> '시간',
	'EMPNEWS_COLUMN_EVENT'		=> '사건',

	// clan news reports
	'CLANNEWS_MEMBER_CREATE'		=> '<b>%1$s</b>이(가) 클랜을 만들었습니다.',
	'CLANNEWS_MEMBER_JOIN'			=> '<b>%1$s</b>이(가) 클랜에 가입했습니다.',
	'CLANNEWS_MEMBER_LEAVE'			=> '<b>%1$s</b>이(가) 클랜에서 탈퇴하였습니다.',
	'CLANNEWS_MEMBER_REMOVE'		=> '<b>%1$s</b>이(가) <b>%2$s</b>을(를) 쫓아냈습니다.',
	'CLANNEWS_MEMBER_DEAD'			=> '<b>%1$s</b>이(가) 멸망하여 클랜에서 사라졌습니다.',
	'CLANNEWS_MEMBER_SHARE'			=> '<b>%1$s</b>의 병력을 공유합니다.',
	'CLANNEWS_MEMBER_UNSHARE'		=> '<b>%1$s</b>의 병력을 더 이상 공유하지 않습니다..',
	'CLANNEWS_PERM_GRANT_LEADER'		=> '<b>%2$s</b>이(가) <b>%1$s</b>에게 Leader직위를 주었습니다.',
	'CLANNEWS_PERM_REVOKE_LEADER'		=> '<b>%1$s</b>이(가) <b>%2$s</b>에 의해 Leader직위에서 해임되었습니다.',
	'CLANNEWS_PERM_REVOKE_LEADER_SELF'	=> '<b>%1$s</b>이(가) 자발적으로 Leader직위를 내려놓았습니다.',
	'CLANNEWS_PERM_GRANT_ASSISTANT'		=> '<b>%2$s</b>이(가) Assistant Leader직위를 <b>%1$s</b>에게 부여하였습니다.',
	'CLANNEWS_PERM_REVOKE_ASSISTANT'	=> '<b>%2$s</b>이(가) <b>%1$s</b>을(를) Assistant Leader직위에서 해임하였습니다.',
	'CLANNEWS_PERM_GRANT_MINISTER'		=> '<b>%2$s</b>이(가) Minister of Foreign Affairs직위를 <b>%1$s</b>에게 부여하였습니다.',
	'CLANNEWS_PERM_REVOKE_MINISTER'		=> '<b>%2$s</b>이(가) <b>%1$s</b>을(를) Minister of Foreign Affairs직위에서 해임하였습니다.',
	'CLANNEWS_PERM_ASSISTANT_INHERIT'	=> '<b>%1$s</b>이(가) <b>%2$s</b>을(를) 대신에서 Assistant Leader 에서 Leader 가 되었습니다.',
	'CLANNEWS_PERM_MINISTER_INHERIT'	=> '<b>%1$s</b>이(가) <b>%2$s</b>을(를) 대신해서 Minister of Foreign Affairs 에서 Leader 가 되었습니다.',
	'CLANNEWS_PERM_MEMBER_INHERIT'		=> '<b>%1$s</b>이(가) <b>%2$s</b>을(를) 대신해서 Leader 가 되었습니다.',
	'CLANNEWS_PROP_CHANGE_PASSWORD'		=> '<b>%1$s</b>이(가) 클랜의 비밀번호를 변경하였습니다.',
	'CLANNEWS_PROP_CHANGE_TITLE'		=> '<b>%1$s</b>이(가) 클랜의 제목을 바꾸었습니다.',
	'CLANNEWS_PROP_CHANGE_URL'		=> '<b>%1$s</b>이(가) 클랜의 홈페이지 주소를 바꾸었습니다.',
	'CLANNEWS_PROP_CHANGE_LOGO'		=> '<b>%1$s</b>이(가) 클랜의 문양을 바꾸었습니다..',
	'CLANNEWS_RECV_WAR_START'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 전쟁을 선언했습니다!',
	'CLANNEWS_RECV_WAR_REQUEST'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 평화 조약을 요구합니다.',
	'CLANNEWS_RECV_WAR_STOP'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 전쟁을 끝내는데 동의했습니다.',
	'CLANNEWS_RECV_WAR_RETRACT'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 평화 조약을 철회앴습니다!',
	'CLANNEWS_RECV_WAR_REJECT'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 당신의 평화 조약을 거절했습니다!',
	'CLANNEWS_RECV_WAR_GONE'		=> '이전에 전쟁 한 <b>%1$s</b> 클랜이 해산했습니다.',
	'CLANNEWS_RECV_ALLY_REQUEST'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 동맹을 원합니다.',
	'CLANNEWS_RECV_ALLY_START'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 당신의 동맹 제의를 수락했습니다.',
	'CLANNEWS_RECV_ALLY_STOP'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 동맹을 끊었습니다!',
	'CLANNEWS_RECV_ALLY_RETRACT'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 동맹 제의를 철회하였습니다!',
	'CLANNEWS_RECV_ALLY_DECLINE'		=> '<b>%2$s</b> 클랜의 <b>%1$s</b>이(가) 당신의 동맹 제의를 거절했습니다.',
	'CLANNEWS_RECV_ALLY_GONE'		=> '이전에 동맹이었던 <b>%1$s</b> 클랜이 해산되었습니다.',
	'CLANNEWS_SEND_WAR_START'		=> '<b>%1$s</b> 클랜이 <b>%2$s</b> 클랜에게 전쟁을 선포했습니다!',
	'CLANNEWS_SEND_WAR_REQUEST'		=> '<b>%1$s</b> 클랜이 <b>%2$s</b> 클랜에게 평화 조약을 요구했습니다.',
	'CLANNEWS_SEND_WAR_STOP'		=> '<b>%1$s</b> 클랜이 <b>%2$s</b> 클랜의 평화 조약에 동의했습니다.',
	'CLANNEWS_SEND_WAR_RETRACT'		=> '<b>%1$s</b> 클랜이 <b>%2$s</b> 클랜의 평화 조약을 철회했습니다!',
	'CLANNEWS_SEND_WAR_REJECT'		=> '<b>%1$s</b> 클랜이 <b>%2$s</b> 클랜의 평화 조약을 거절했습니다!',
	'CLANNEWS_SEND_ALLY_REQUEST'		=> '<b>%1$s</b> 클랜이 <b>%2$s</b> 클랜과의 동맹을 제안했습니다.',
	'CLANNEWS_SEND_ALLY_START'		=> '<b>%1$s</b> 클랜이 <b>%2$s</b> 클랜과의 동맹을 승락했습니다.',
	'CLANNEWS_SEND_ALLY_STOP'		=> '<b>%1$s</b> 클랜이 <b>%2$s</b> 클랜과의 동맹을 끊었습니다.',
	'CLANNEWS_SEND_ALLY_RETRACT'		=> '<b>%1$s</b> retracted your offer of alliance from clan <b>%2$s</b>.',
	'CLANNEWS_SEND_ALLY_DECLINE'		=> '<b>%1$s</b> declined the alliance request from clan <b>%2$s</b>.',
	'CLANNEWS_COLUMN_TIME'			=> '시간',
	'CLANNEWS_COLUMN_EVENT'			=> '사건',

	// special effects
	'EFFECT_SHIELD'			=> '앞으로 %1$s 시간 이후 까지 마법 방어막이 작동합니다.',
	'EFFECT_GATE'			=> '앞으로 %1$s 시간 이후 까지 시간의 문이 작동합니다.',

	// other
	'HTML_TITLE'			=> 'Promisance - %1$s',
	'HTML_FOOTER'			=> 'Promisance v%1$s<br />Copyright © 2001-2008 <a href="http://www.qmtpro.com/">QMT Productions</a><br />한글판 by bandocheman',
	'HTML_LINK_CREDITS'		=> '제작자 보기',
	'HTML_LINK_LOGIN'		=> '로그인으로 돌아가기',
	'MENU_HEADER_TOP'		=> '화생공<br/>연대기',
	'MENU_LINK_MAIN'		=> '메인 메뉴',
	'MENU_HEADER_INFO'		=> '정보',
	'MENU_LINK_GUIDE'		=> '게임 가이드',
	'MENU_LINK_STATUS'		=> '제국 상태',
	'MENU_LINK_SCORES'		=> '점수',
	'MENU_LINK_GRAVEYARD'		=> '무덤',
	'MENU_LINK_SEARCH'		=> '제국 검색',
	'MENU_LINK_NEWS'		=> '소식 검색',
	'MENU_LINK_CONTACTS'		=> '클랜 연락처',
	'MENU_LINK_CLANSTATS'		=> '클랜 통계',
	'MENU_LINK_FORUMS'		=> '포럼',
	'MENU_HEADER_TURNS'		=> '턴 사용하기',
	'MENU_LINK_FARM'		=> '농사 짓기',
	'MENU_LINK_CASH'		=> '돈 벌기',
	'MENU_LINK_LAND'		=> '탐색 활동',
	'MENU_LINK_BUILD'		=> '건물 짓기',
	'MENU_HEADER_MONEY'		=> '금융',
	'MENU_LINK_PVTMARKETBUY'	=> '암시장',
	'MENU_LINK_PUBMARKETBUY'	=> '공공 시장',
	'MENU_LINK_BANK'		=> '세계 은행',
	'MENU_LINK_LOTTERY'		=> '복권',
	'MENU_HEADER_FOREIGN'		=> '대외 관계',
	'MENU_LINK_AID'			=> '외국 원조',
	'MENU_LINK_CLAN'		=> '클랜',
	'MENU_LINK_MILITARY'		=> '전쟁처',
	'MENU_LINK_MAGIC'		=> '마법처',
	'MENU_HEADER_MANAGE'		=> '관리',
	'MENU_LINK_MESSAGES'		=> '메시지',
	'MENU_LINK_MANAGE'		=> '제국 관리',
	'MENU_LINK_DELETE'		=> '계정 삭제',
	'MENU_HEADER_ADMIN'		=> '운영',
	'MENU_HEADER_MODERATOR'		=> '부운영자',
	'MENU_LINK_ADMIN_USERS'		=> '사용자',
	'MENU_LINK_ADMIN_EMPIRES'	=> '제국',
	'MENU_LINK_ADMIN_CLANS'		=> '클랜',
	'MENU_LINK_ADMIN_MESSAGES'	=> '메시지',
	'MENU_LINK_ADMIN_PERMISSIONS'	=> '권한',
	'MENU_LINK_ADMIN_ROUND'		=> '판',
	'MENU_LINK_ADMIN_LOCKS'		=> 'DB Locks',
	'MENU_LINK_ADMIN_LOG'		=> '이벤트 기록',
	'MENU_LINK_ADMIN_MARKET'	=> '상점',
	'MENU_LINK_ADMIN_HISTORY'	=> '기록',
	'MENU_LINK_LOGOUT'		=> '로그 아웃',
	'HTML_BONUS_SUBMIT'		=> '보너스 턴 모우기',
	'HTML_SORT_ASCEND'		=> '▲',
	'HTML_SORT_DESCEND'		=> '▼',
	'STATBAR_NEWMAIL'		=> '새 편지가 왔습니다!',
	'STATBAR_MAILBOX'		=> '편지함',
	'EMAIL_FROM'			=> 'Promisance Web Game',
	'VALIDATION_EMAIL_SUBJECT'	=> 'Promisance validation code! %1$s - %2$s',
	'VALIDATION_EMAIL_BODY'		=> <<<END_MESSAGE
%1\$s에 가입해주셔서 감사합니다!

----------------------------------------------------------------------
여러분이 가입하실 때 입력한 정보입니다.:
사용자 이름: %2\$s
제국 이름: %3\$s

인증 번호: %4\$s

 %5\$s 턴을 소요하고 나면 해당 게임을 계속 하기 위해서는 인증 번호가 필요합니다.
또한 이 인증 번호는 계정을 삭제할 때도 필요합니다.
----------------------------------------------------------------------

여러분의 e-mail 주소는 안전하게 보관되고, 다른 사람들에게 주지 않습니다.

%6\$s

의문 사항은 아래의 메일로 보내주세요.
%7\$s

만약 여러분이 이 게임에 가입한 적이 없다면, 이 메일은 무시하셔도 됩니다.
If you did not sign up for an account in this game, you may safely
ignore this message.
END_MESSAGE
	,
);
?>
