<?
/* QM Promisance - Turn-based strategy game
 * Copyright (C) 2001-2008 QMT Productions
 *
 * $URL: https://qmpromisance.svn.sourceforge.net/svnroot/qmpromisance/promisance/tags/release-4_0/lang/ko-KR/pages.php $
 * $Id: pages.php 1360 2009-01-01 21:27:41Z Quietust $
 */

if (!defined('IN_GAME') && !defined('IN_TURNS'))
	die("Access denied");

$lang['ko-KR'] += array(
	// pages/aid
	'AID_TITLE'			=> '해외 원조',
	'AID_UNAVAILABLE_START'		=> '이번 판이 시작하기 전에 해외에 원조를 보낼 수 없습니다.',
	'AID_UNAVAILABLE_END'		=> '이번 판이 끝난 후에 해외에 원조를 보낼 수 없습니다.',
	'AID_UNAVAILABLE_PROTECT'	=> '보호 받는 동안 해외에 원조를 할 수 없습니다.',
	'AID_UNAVAILABLE_ADMIN'		=> '관리자 권한에 의해서 해외에 원조를 보낼 수 없습니다.',
	'AID_UNAVAILABLE_CONFIG'	=> '이번 게임에서는 해외에 원조를 보낼 수 없습니다.',
	'AID_NEED_CREDITS'		=> '지금 더 원조를 보낼 수 없습니다. 한 시간 후에 다시 오세요.',
	'AID_NEED_TURNS'		=> '원조를 보낼 수 있는 턴이 부족합니다!',
	'AID_TARGET_DEAD'		=> '그 제국은 이미 멸망했습니다. 원조 보내도 소용없습니다.',
	'AID_TARGET_DELETED'		=> '그 제국은 이미 삭제되었습니다. 선물 받을 사람이 없네요..',
	'AID_TARGET_GATE'		=> '시간의 문을 열기 전에는 다른 시대에 있는 제국으로 원조를 보낼 수 없습니다!',
	'AID_TARGET_ADMIN'		=> '관리자에게 원조를 보낼 수 없습니다!',
	'AID_TARGET_DISABLED'		=> '그 제국은 관리자가 잠궈두었기 때문에 원조를 보낼 수 없습니다.',
	'AID_TARGET_PROTECTED'		=> '아직 초보자 보호를 받고 있는 제국에게는 원조를 보낼 수 없습니다!',
	'AID_TARGET_VACATION'		=> '현재 휴가를 떠난 제국으로 원조를 보낼 수 없습니다!',
	'AID_TARGET_WAR'		=> '전쟁중인 국가에 원조를 보내는게 말이 된다고 생각합니까?',
	'AID_TARGET_TOO_BIG'		=> '당신보다 훨씬 강한 국가에게 원조 보낼 필요가 없습니다.',
	'AID_NEED_CONVOY'		=> '원조 보낼 %1$s이(가) 부족합니다!',
	'AID_TOO_MUCH_CASH'		=> '한 번에 그렇게 많은 돈을 보낼 수 없습니다. %1$s 만큼만 보냈습니다.',
	'AID_TOO_MUCH_UNIT'		=> '한 번에 그렇게 많은 %1$s을(를) 보낼 수 없습니다. %2$s 만큼만 보냈습니다.',
	'AID_COMPLETE'			=> '%2$s %1$s개가 <b>%3$s</b>에 도착했습니다.',
	'AID_WILL_RETURN'		=> '남은 %2$s %1$s개가 다시 돌아올것입니다.',
	'AID_HEADER'			=> '원조를 보내는데 2 턴이 필요하고 %2$s %1$s개가 필요합니다.<br />지금은 %3$s을(를) 보낼 수 있습니다.<br />매 시간마다 추가적인 원조도 보낼 수 있습니다.',
	'AID_SUBMIT'			=> '지원 보내기',

	// pages/bank
	'BANK_TITLE'			=> '세계 은행',
	'BANK_UNAVAILABLE_START'	=> '이번 판이 시작하기 전에 은행 업무를 볼 수 없습니다.',
	'BANK_UNAVAILABLE_END'		=> '이번 판이 끝난 후에 은행 업무를 볼 수 없습니다.',
	'BANK_BORROW_TOO_LATE'		=> '이번 판이 끝날 때 되어서 돈을 빌릴 수 없습니다!',
	'BANK_BORROW_TOO_MUCH'		=> '대출 한도를 초과하셨습니다!',
	'BANK_BORROW_COMPLETE'		=> '%1$s 대출하셨습니다. 매 턴 마다 0.5%% 이자를 내야 됩니다.',
	'BANK_REPAY_NOT_ENOUGH'		=> '상환 할 돈이 부족합니다!',
	'BANK_REPAY_COMPLETE'		=> '%1$s 상환 감사합니다. 신용 등급이 즉시 상향되었습니다.',
	'BANK_DEPOSIT_NOT_ENOUGH'	=> '예금 할 돈이 부족합니다!',
	'BANK_DEPOSIT_TOO_MUCH'		=> '그렇게 많은 돈을 맡길 수 없습니다!',
	'BANK_DEPOSIT_COMPLETE'		=> '%1$s을 정상적으로 입금했습니다.',
	'BANK_WITHDRAW_COMPLETE'	=> '%1$s을 정상적으로 출금했습니다.',
	'BANK_HEADER_SAVINGS'		=> '저축',
	'BANK_HEADER_LOAN'		=> '대출',
	'BANK_LABEL_SAVINGS_INTEREST'	=> 'APR당 이율:',
	'BANK_LABEL_LOAN_INTEREST'	=> 'APR당 이율:',
	'BANK_LABEL_MAX_SAVINGS'	=> '저축 한도:',
	'BANK_LABEL_MAX_LOAN'		=> '대출 한도:',
	'BANK_LABEL_CUR_SAVINGS'	=> '현재 저축금:',
	'BANK_LABEL_CUR_LOAN'		=> '현재 대출금:',
	'BANK_INTEREST_DESCRIPTION'	=> '이자은 매 턴마다 계산합니다. (52 턴 = 1 APR년)',
	'BANK_SAVINGS_INTEREST_PROTECT'	=> '(보호 받는 중에는 저축 이자를 받지 못합니다.)',
	'BANK_LOAN_UNAVAILABLE'		=> '이번 판이 끝나는주에는 대출을 받지 못합니다.',
	'BANK_LABEL_BORROW'		=> '대출 받기',
	'BANK_LABEL_REPAY'		=> '대출 갚기',
	'BANK_LABEL_DEPOSIT'		=> '저축 예금',
	'BANK_LABEL_WITHDRAW'		=> '저축 출금',
	'BANK_BORROW_SUBMIT'		=> '대출',
	'BANK_REPAY_SUBMIT'		=> '상환',
	'BANK_DEPOSIT_SUBMIT'		=> '입금',
	'BANK_WITHDRAW_SUBMIT'		=> '출금',

	// pages/build
	'BUILD_TITLE'			=> '건설',
	'BUILD_UNAVAILABLE_START'	=> '이번 판이 시작하기전 부터 건설할 수 없습니다.',
	'BUILD_UNAVAILABLE_END'		=> '이번 판이 끝난 이후에 건설할 수 없습니다.',
	'BUILD_NO_INPUT'		=> '얼마나 많이 건설을 원하는지 입력해주세요.',
	'BUILD_TOO_MANY'		=> '그렇게 많이 지을 수 없습니다!',
	'BUILD_COMPLETE'		=> '%2$s 동안 %1$s으로 %3$s을(를) 건설하였습니다.',
	'BUILD_HEADER'			=> '모든 건축물들은 한 평을 차지하고, 만드는데 비용이 %1$s 소요됩니다.<br />매 턴 마다 %2$s개의 건축물을 만들 수 있습니다.<br />현재의 자원으로는 최대 <span class="cgood">%3$s</span>개 까지 건설 가능합니다.<br />',
	'BUILD_LABEL_FREELAND'		=> '쓰지 않는 땅',
	'BUILD_SUBMIT'			=> '건설 시작',
	'BUILD_LINK_DEMOLISH'		=> '건물 파괴',

	// pages/cash
	'CASH_TITLE'			=> '경제 집중',
	'CASH_NOT_ENOUGH_TURNS'		=> '그렇게 많은 턴 동안 돈을 벌 수 없습니다!(턴 부족)',
	'CASH_SPECIFY_TURNS'		=> '경제에 집중할 정확한 턴을 입력해주세요.',
	'CASH_COMPLETE'			=> '%2$s턴 동안 %1$s 벌었습니다.',
	'CASH_HEADER'			=> '경제에 집중하는 동안 %1$s이(가) 25%% 더 많은 돈을 벌어옵니다.',
	'CASH_LABEL'			=> '얼만큼의 턴 동안 경제에 집중하시겠습니까?',
	'CASH_SUBMIT'			=> '경제에 집중',

	// pages/clan
	'CLAN_TITLE'			=> '클랜',
	'CLAN_UNAVAILABLE_START'	=> '이번 판이 시작하기 전에 클랜을 확인할 수 없습니다.',
	'CLAN_UNAVAILABLE_END'		=> '이번 판이 끝난 후에 클랜에 접근할 수 없습니다.',
	'CLAN_UNAVAILABLE_PROTECT'	=> '보호 받는 동안 클랜에 접근할 수 없습니다.',
	'CLAN_UNAVAILABLE_ADMIN'	=> '관리자 권한에 의해서 클랜에 접근할 수 없습니다.',
	'CLAN_UNAVAILABLE_CONFIG'	=> '클랜 기능은 이번 판에서는 사용할 수 없습니다.',

	'CLAN_ALREADY_MEMBER'		=> '이미 클랜에 가입해 있습니다!',
	'CLAN_NOT_MEMBER'		=> '아무 클랜에도 가입하지 않았습니다!',

	'CLAN_CREATE_TOO_LATE'		=> '클랜을 만들기에는 너무 늦었습니다.',
	'CLAN_CREATE_TOO_SOON'		=> '이전 클랜을 떠난지 %1$s 시간이 지나야 새로운 클랜을 만들 수 있습니다.',
	'CLAN_CREATE_NEED_NAME'		=> '새 클랜의 이름을 정해주세요.',
	'CLAN_CREATE_NAME_INVALID'	=> '그 이름은 사용할 수 없습니다!',
	'CLAN_CREATE_NAME_TOO_LONG'	=> '더 짧은 이름으로 바꿔주세요',
	'CLAN_CREATE_NAME_IN_USE'	=> '이미 사용중인 클랜 이름입니다. 다른 이름을 생각해보세요.',
	// Only used with default language
	'CLAN_CREATE_DEFAULT_TITLE'	=> '클랜 %1$s',
	// Only used with default language
	'CLAN_CREATE_DEFAULT_MOTD'	=> '%1$s 클랜에 오신것을 환영합니다!',
	'CLAN_CREATE_COMPLETE'		=> '%1$s 클랜을 만드셨습니다.',

	'CLAN_JOIN_TOO_SOON'		=> '이전 클랜을 떠난지 %1$s 시간이 지나야 다른 클랜에 가입할 수 있습니다.',
	'CLAN_JOIN_NEED_CLAN'		=> '가입할 클랜을 입력해주세요!',
	'CLAN_JOIN_IS_FULL'		=> '죄송합니다. 지금 그 클랜에는 빈자리가 없습니다. 다른 사람이 클랜을 떠나거나 더 많은 제국이 생기게 되면 다시 와주세요.',
	'CLAN_JOIN_COMPLETE'		=> '이제 %1$s 클랜원이 되었습니다.',

	'CLAN_LEAVE_TOO_SOON'		=> '클랜에 가입하고 %1$s 시간 동안은 다시 나갈 수 없습니다.',
	'CLAN_LEAVE_NEED_CONFIRM'	=> '클랜에 탈퇴하려면 아래 확인란을 선택해주셔야됩니다!',
	'CLAN_LEAVE_IS_FULL'		=> '해당 클랜은 다 찼습니다. 다른 사람이 클랜을 나가거나 더 많은 제국이 생길 때 까지 기다려주세요.',
	'CLAN_LEAVE_OTHER_MEMBERS'	=> '클랜의 다른 회원들을 버릴 수 없습니다!',
	'CLAN_LEAVE_COMPLETE_DISBAND'	=> '당신의 클랜 %1$s, 드디어 해체되었습니다.',
	'CLAN_LEAVE_COMPLETE'		=> '당신은 이제 %1$s에서 탈퇴하였습니다.',

	'CLAN_SHARE_COMPLETE'		=> '당신은 이제 다른 클랜원들과 함께 병력을 공유합니다.',
	'CLAN_UNSHARE_COMPLETE'		=> '%1$s 시간이 지나면 당신의 병력은 당신의 방어에만 사용합니다.',

	'CLAN_LINK_LABEL'		=> '%1$s의 홈페이지',
	'CLAN_MEMBER_HEADER'		=> '클랜 <i>%1$s</i>의 정보',
	'CLAN_LINK_FORUM'		=> '클랜 포럼',
	'CLAN_LINK_MANAGE'		=> '클랜 관리',
	'CLAN_RELATIONS_HEADER'		=> '%1$s 대외 관계',
	'CLAN_ALLY_LABEL'		=> '동맹',
	'CLAN_ALLY_DESC'		=> '공격 불가능<br />무제한 원조',
	'CLAN_WAR_LABEL'		=> '전쟁중',
	'CLAN_WAR_DESC'			=> '무제한 공격/마법 공격<br />원조 불가능',
	'CLAN_ALLY_MUTUAL_LABEL'	=> '동맹 구축',
	'CLAN_ALLY_OUTBOUND_LABEL'	=> '보낸 요구사항',
	'CLAN_ALLY_INBOUND_LABEL'	=> '받은 요구사항',
	'CLAN_ALLY_NONE_LABEL'		=> '동맹 없음',
	'CLAN_WAR_MUTUAL_LABEL'		=> '전쟁중',
	'CLAN_WAR_OUTBOUND_LABEL'	=> 'Outgoing Concessions',
	'CLAN_WAR_INBOUND_LABEL'	=> 'Incoming Concessions',
	'CLAN_WAR_NONE_LABEL'		=> '전쟁 없음',
	'CLAN_UNSHARE_SUBMIT'		=> '클랜원이 방어중일 때 나의 병력 사용하지 않기',
	'CLAN_SHARE_SUBMIT'		=> '클랜원이 방어중일 때 나의 병력 지원하기',
	'CLAN_MEMBERS_HEADER'		=> '%1$s currently has %2$s members.',
	'CLAN_MEMBERS_LABEL'		=> '회원 목록',
	'CLAN_LEADER_LABEL'		=> '지도자',
	'CLAN_ASSISTANT_LABEL'		=> '보조',
	'CLAN_FA_LABEL'			=> '장관',
	'CLAN_SHARE_HEADER'		=> '클랜이 공유하는 방어력',
	'CLAN_UNSHARE_HEADER'		=> ' (%1$s분 이상)',
	'CLAN_DISBAND_SUBMIT'		=> '클랜 해체',
	'CLAN_DISBAND_CONFIRM'		=> '정말 클랜 해체를 원합니다!',
	'CLAN_LEAVE_SUBMIT'		=> '클랜 떠나기',
	'CLAN_LEAVE_CONFIRM'		=> '정말 클랜을 떠날것입니다!',

	'CLAN_NONMEMBER_HEADER'		=> '세상은 무서운 곳 입니다. 클랜에 가입하거나 클랜에 들어가는것이 좋을 것입니다.',
	'CLAN_JOIN_LABEL'		=> '클랜 가입',
	'CLAN_JOIN_LABEL_WITH_TITLE'	=> '%1$s - %2$s',
	'CLAN_JOIN_SUBMIT'		=> '클랜 가입 신청',
	'CLAN_JOIN_NONE_AVAILABLE'	=> '아직 클랜이 아무것도 없습니다. 최초의 클랜을 만드세요!',
	'CLAN_JOIN_NONE_UNAVAILABLE'	=> '아쉽지만 가입할 수 있는 클랜도 없고, 더 이상 클랜을 만들수도 없습니다.',
	'CLAN_CREATE_LABEL'		=> '클랜 만들기',
	'CLAN_CREATE_SUBMIT'		=> '클랜 만들기',

	// pages/clanforum
	'CLANFORUM_TITLE'		=> '클랜 포럼',
	'CLANFORUM_UNAVAILABLE_START'	=> '이번 판이 시작하기 전에 클랜 포럼에 접속할 수 없습니다.',
	'CLANFORUM_UNAVAILABLE_END'	=> '이번 판이 끝난 후에 클랜 포럼에 접속할 수 없습니다.',
	'CLANFORUM_UNAVAILABLE_PROTECT'	=> '보호 받는 동안 클랜 포럼에 접속할 수 없습니다.',
	'CLANFORUM_UNAVAILABLE_ADMIN'	=> '관리자는 클랜 포럼에 접속할 수 없습니다',
	'CLANFORUM_UNAVAILABLE_CONFIG'	=> '이번 게임에서는 클랜을 사용할 수 없습니다.',

	'CLANFORUM_SUBJECT_TOO_LONG'	=> 'Message subject is too long!',
	'CLANFORUM_SUBJECT_INVALID'	=> 'You cannot use that text for your message subject!',
	'CLANFORUM_BODY_TOO_LONG'	=> 'Message size limit exceeded - please shorten your message and try again.',
	'CLANFORUM_BODY_INVALID'	=> 'You cannot use that text for your message body!',
	'CLANFORUM_TOPIC_NOT_EXIST'	=> 'The specified thread does not exist.',
	'CLANFORUM_TOPIC_WRONG_CLAN'	=> 'You specified thread is in another clan\'s forum!',
	'CLANFORUM_MESSAGE_NOT_EXIST'	=> 'The specified post does not exist.',

	'CLANFORUM_POST_COMPLETE'	=> 'Your message has been successfully posted in a new thread.',

	'CLANFORUM_REPLY_LOCKED'	=> 'This thread has been locked - you may not post in it.',
	'CLANFORUM_REPLY_NEWS'		=> 'You are not allowed to post messages in your clan\'s 소식 thread!',
	'CLANFORUM_REPLY_COMPLETE'	=> 'Your reply has been successfully posted.',

	'CLANFORUM_EDIT_LOCKED'		=> 'This thread has been locked - you may not edit posts in it.',
	'CLANFORUM_EDIT_NEWS'		=> 'You are not allowed to edit messages in your clan\'s 소식 thread!',
	'CLANFORUM_EDIT_PERMISSION'	=> 'You are not allowed to edit messages posted by other players!',
	'CLANFORUM_EDIT_TOO_LATE'	=> 'Your post has already been replied to - you may no longer edit it.',
	'CLANFORUM_EDIT_COMPLETE'	=> 'The specified post has been successfully edited.',

	'CLANFORUM_DELETE_LOCKED'	=> 'This thread has been locked - you may not delete posts from it.',
	'CLANFORUM_DELETE_NEWS'		=> 'You are not allowed to edit messages in your clan\'s 소식 thread!',
	'CLANFORUM_DELETE_PERMISSION'	=> 'You are not allowed to delete messages posted by other players!',
	'CLANFORUM_DELETE_TOO_LATE'	=> 'Your post has already been replied to - you may no longer delete it.',
	'CLANFORUM_DELETE_CANNOT_NEWS'	=> 'You cannot delete your clan\'s 소식 thread!',
	'CLANFORUM_DELETE_MESSAGE_COMPLETE'	=> 'The specified post has been successfully deleted.',
	'CLANFORUM_DELETE_TOPIC_COMPLETE'	=> 'The specified thread has been successfully deleted.',

	'CLANFORUM_LINK_INDEX'		=> 'Forum Index',
	'CLANFORUM_SUBJECT_NEWS'	=> '클랜 소식',
	'CLANFORUM_SUBJECT_SEP'		=> ' :: ',
	'CLANFORUM_NONMEMBER_LABEL'	=> 'Former Member',
	'CLANFORUM_FA_LABEL'		=> 'Minister of Foreign Affairs',
	'CLANFORUM_MEMBER_LABEL'	=> 'Member',
	'CLANFORUM_LABEL_EDIT'		=> 'Edit Post:',
	'CLANFORUM_FLAG_STICKY'		=> 'Sticky',
	'CLANFORUM_FLAG_LOCKED'		=> 'Lock Topic',

	'CLANFORUM_EDIT_SUBMIT'		=> 'Submit',
	'CLANFORUM_EDIT_CANCEL'		=> 'Cancel',

	'CLANFORUM_DELETE_PROMPT_MESSAGE'	=> 'Are you sure you wish to delete this post?',
	'CLANFORUM_DELETE_PROMPT_TOPIC'		=> 'Are you sure you wish to delete this post and all of its replies?',

	'CLANFORUM_SUBMIT_EDIT'		=> '[Edit]',
	'CLANFORUM_SUBMIT_DELETE'	=> '[Delete]',
	'CLANFORUM_SUBMIT_QUOTE'	=> '[Quote]',

	'CLANFORUM_LABEL_REPLY'		=> 'Post Reply:',
	'CLANFORUM_REPLY_SUBMIT'	=> 'Submit',

	'CLANFORUM_COLUMN_AUTHOR'	=> 'Author',
	'CLANFORUM_COLUMN_MESSAGE'	=> 'Message',
	'CLANFORUM_COLUMN_TOPICS'	=> 'Topics',
	'CLANFORUM_COLUMN_REPLIES'	=> 'Replies',
	'CLANFORUM_COLUMN_LASTPOST'	=> 'Last Post',

	'CLANFORUM_ICON_NEWS'		=> '!',
	'CLANFORUM_ICON_STICKY'		=> '*',
	'CLANFORUM_ICON_LOCKED'		=> 'X',

	'CLANFORUM_POST_SUBMIT'		=> 'Post',

	// pages/clanmanage
	'CLANMANAGE_TITLE'		=> '클랜들',
	'CLANMANAGE_UNAVAILABLE_START'	=> '클랜들 cannot be accessed 이번 판이 시작하기 전에 할 수 없습니다.',
	'CLANMANAGE_UNAVAILABLE_END'	=> '클랜들 cannot be accessed 이번 판이 끝난 후에 할 수 없습니다.',
	'CLANMANAGE_UNAVAILABLE_PROTECT'=> '클랜들 cannot be accessed 보호 받는 동안 할 수 없습니다.',
	'CLANMANAGE_UNAVAILABLE_ADMIN'	=> '클랜들 cannot be accessed 관리자 권한에 의해서',
	'CLANMANAGE_UNAVAILABLE_CONFIG'	=> '클랜들 are not available in this game.',
	'CLANMANAGE_NEED_PERMISSION'	=> 'You do not have administrative authority in this clan!',

	'CLANMANAGE_NO_SUCH_CLAN'	=> 'The clan you selected does not exist!',
	'CLANMANAGE_NO_SUCH_RELATION'	=> 'The selected clan relation does not exist!',
	'CLANMANAGE_INVALID_RELATION'	=> 'You have selected an invalid relation!',
	'CLANMANAGE_CLAN_IS_GONE'	=> 'The clan you selected no longer exists!',

	'CLANMANAGE_ALLY_REQUEST_TOO_MANY'	=> 'Your clan cannot request any more alliances at this time.',
	'CLANMANAGE_ALLY_REQUEST_ALREADY_ALLY_ACCEPTED'		=> 'You have already established an alliance with <b>%1$s</b>!',
	'CLANMANAGE_ALLY_REQUEST_ALREADY_ALLY_REQUESTED'	=> 'You have already requested an alliance with <b>%1$s</b>!',
	'CLANMANAGE_ALLY_REQUEST_ALREADY_ALLY_PENDING'		=> '<b>%1$s</b> has already requested an alliance with you!',
	'CLANMANAGE_ALLY_REQUEST_ALREADY_WAR_DECLARED_IN'	=> 'You cannot request an alliance with <b>%1$s</b> - they are at war with you!',
	'CLANMANAGE_ALLY_REQUEST_ALREADY_WAR_DECLARED_OUT'	=> 'You cannot request an alliance with <b>%1$s</b> - you are at war with them!',
	'CLANMANAGE_ALLY_REQUEST_ALREADY_WAR_REQUESTED_IN'	=> 'You cannot request an alliance with <b>%1$s</b> yet - you must first accept their peace treaty!',
	'CLANMANAGE_ALLY_REQUEST_ALREADY_WAR_REQUESTED_OUT'	=> 'You cannot request an alliance with <b>%1$s</b> yet - you must first allow them to accept your peace treaty!',
	'CLANMANAGE_ALLY_REQUEST_COMPLETE'	=> 'You have requested an alliance alliance with <b>%1$s</b>.',
	'CLANMANAGE_ALLY_CANCEL_TOO_SOON'	=> 'You cannot cancel an alliance request so soon!',
	'CLANMANAGE_ALLY_CANCEL_COMPLETE'	=> 'You have retracted your clan\'s request for alliance with <b>%1$s</b>.',
	'CLANMANAGE_ALLY_ACCEPT_SELF_TOO_MANY'	=> 'Your clan cannot form any more alliances at this time.',
	'CLANMANAGE_ALLY_ACCEPT_OTHER_TOO_MANY'	=> 'Your companion clan cannot form any more alliances at this time.',
	'CLANMANAGE_ALLY_ACCEPT_COMPLETE'	=> 'You have accepted <b>%1$s</b>\'s request for an alliance!',
	'CLANMANAGE_ALLY_DENY_COMPLETE'	=> 'You have declined <b>%1$s</b>\'s request for an alliance.',
	'CLANMANAGE_ALLY_STOP_NEED_CONFIRM'	=> 'You must check the confirmation box in order to terminate an alliance.',
	'CLANMANAGE_ALLY_STOP_TOO_SOON'	=> 'You cannot terminate an alliance so soon!',
	'CLANMANAGE_ALLY_STOP_COMPLETE'	=> 'You have terminated your clan\'s alliance with <b>%1$s</b>.',

	'CLANMANAGE_WAR_DECLARE_TOO_MANY'	=> 'Your clan does not have the resources to engage in any more wars.',
	'CLANMANAGE_WAR_DECLARE_ALREADY_ALLY_ACCEPTED'		=> 'You cannot declare war with <b>%1$s</b> - they are your allies!',
	'CLANMANAGE_WAR_DECLARE_ALREADY_ALLY_REQUESTED'		=> 'You cannot declare war with <b>%1$s</b> yet - you must first retract your request for alliance!',
	'CLANMANAGE_WAR_DECLARE_ALREADY_ALLY_PENDING'		=> 'You cannot declare war with <b>%1$s</b> yet - you must first decline their request for alliance!',
	'CLANMANAGE_WAR_DECLARE_ALREADY_WAR_DECLARED_IN'	=> '<b>%1$s</b> is already at war with you!',
	'CLANMANAGE_WAR_DECLARE_ALREADY_WAR_DECLARED_OUT'	=> 'You are already at war with <b>%1$s</b>!',
	'CLANMANAGE_WAR_DECLARE_ALREADY_WAR_REQUESTED_IN'	=> '<b>%1$s</b> has already requested a peace treaty with you!',
	'CLANMANAGE_WAR_DECLARE_ALREADY_WAR_REQUESTED_OUT'	=> 'You have already requested a peace treaty with <b>%1$s</b>!',
	'CLANMANAGE_WAR_DECLARE_COMPLETE'	=> 'You have declared war with <b>%1$s</b>.',
	'CLANMANAGE_WAR_REQUEST_NEED_CONFIRM'	=> 'You must check the confirmation box in order to propose a treaty.',
	'CLANMANAGE_WAR_REQUEST_TOO_SOON'	=> 'You cannot end a war so soon!',
	'CLANMANAGE_WAR_REQUEST_COMPLETE'	=> 'You have proposed a peace treaty with <b>%1$s</b>.',
	'CLANMANAGE_WAR_RESUME_TOO_SOON'	=> 'You cannot resume a war so soon!',
	'CLANMANAGE_WAR_RESUME_COMPLETE'	=> 'You have retracted your peace treaty proposition from <b>%1$s</b>.',
	'CLANMANAGE_WAR_REJECT_NEED_CONFIRM'	=> 'You must check the confirmation box in order to reject a treaty.',
	'CLANMANAGE_WAR_REJECT_TOO_MANY'	=> 'Your clan does not have the resources to take the offensive in this war.',
	'CLANMANAGE_WAR_REJECT_COMPLETE'	=> 'You have rejected <b>%1$s</b>\'s peace treaty!',
	'CLANMANAGE_WAR_STOP_COMPLETE'	=> 'You accept <b>%1$s</b>\'s peace treaty and end the war.',

	'CLANMANAGE_PASSWORD_NEED_PERMISSION'	=> 'You are not allowed to change your clan\'s password!',
	'CLANMANAGE_PASSWORD_COMPLETE'	=> 'Your clan password has been changed.',
	'CLANMANAGE_LOGO_NEED_PERMISSION'	=> 'You are not allowed to change your clan\'s logo!',
	'CLANMANAGE_LOGO_TOO_LONG'	=> '클랜 logo URL is too long!',
	'CLANMANAGE_LOGO_INVALID'	=> 'You must specify a valid URL for your clan logo!',
	'CLANMANAGE_LOGO_COMPLETE'	=> '클랜 logo changed.',
	'CLANMANAGE_TITLE_NEED_PERMISSION'	=> 'You are not allowed to change your clan\'s title!',
	'CLANMANAGE_TITLE_REQUIRED'	=> 'You cannot remove your clan title!',
	'CLANMANAGE_TITLE_TOO_LONG'	=> '클랜 title is too long!',
	'CLANMANAGE_TITLE_INVALID'	=> 'That clan title is not allowed!',
	'CLANMANAGE_TITLE_COMPLETE'	=> '클랜 title changed.',
	'CLANMANAGE_URL_NEED_PERMISSION'	=> 'You are not allowed to change your clan\'s homepage!',
	'CLANMANAGE_URL_TOO_LONG'	=> '클랜 homepage URL is too long!',
	'CLANMANAGE_URL_INVALID'	=> 'You must specify a valid URL for your clan homepage!',
	'CLANMANAGE_URL_COMPLETE'	=> '클랜 homepage changed.',

	'CLANMANAGE_RANKS_NEED_PERMISSION'	=> 'You are not allowed to alter clan ranks or remove members!',
	'CLANMANAGE_RANKS_REMOVE_NOT_IN_CLAN'	=> 'That empire is not in this clan!',
	'CLANMANAGE_RANKS_REMOVE_IS_SPECIAL'	=> 'You may not remove a member who is in a position of authority!',
	'CLANMANAGE_RANKS_REMOVE_COMPLETE'	=> 'You have removed <b>%1$s</b> from your clan.',
	'CLANMANAGE_RANKS_CHANGE_LEADER_PERMISSION'	=> 'Only the current clan leader can appoint a new leader!',
	'CLANMANAGE_RANKS_CHANGE_ASST_PERMISSION'	=> 'Only the current clan leader can appoint a new assistant leader!',
	'CLANMANAGE_RANKS_ASST_REMOVED'	=> '<b>%1$s</b> is no longer the Assistant Leader of <b>%2$s</b>.',
	'CLANMANAGE_RANKS_FA_REMOVED'	=> '<b>%1$s</b> is no longer a Minister of Foreign Affairs of <b>%2$s</b>.',
	'CLANMANAGE_RANKS_NEED_LEADER'	=> 'You must select an empire to be your clan leader!',
	'CLANMANAGE_RANKS_CONFLICT'	=> 'You cannot assign multiple positions of authority to a single empire!',
	'CLANMANAGE_RANKS_WRONG_CLAN'	=> 'You cannot assign a position of authority to an empire not in our clan!',
	'CLANMANAGE_RANKS_LEADER_GONE'	=> 'The empire you selected for clan leader does not exist!',
	'CLANMANAGE_RANKS_LEADER_ADDED'	=> '<b>%1$s</b> is now the Leader of <b>%2$s</b>.',
	'CLANMANAGE_RANKS_ASST_GONE'	=> 'The empire you selected for assistant leader does not exist!',
	'CLANMANAGE_RANKS_ASST_ADDED'	=> '<b>%1$s</b> is now the Assistant Leader of <b>%2$s</b>.',
	'CLANMANAGE_RANKS_FA_GONE'	=> 'The empire you selected for Minister of Foreign Affairs does not exist!',
	'CLANMANAGE_RANKS_FA_ADDED'	=> '<b>%1$s</b> is now a Minister of Foreign Affairs of <b>%2$s</b>.',

	'CLANMANAGE_HEADER'		=> '클랜 Management for <i>%1$s</i>',
	'CLANMANAGE_RELATION_STATUS'	=> 'Status: <b>%1$s</b><br />since %2$s',
	'CLANMANAGE_RELATION_STATUS_ALLY_MUTUAL'	=> 'Active',
	'CLANMANAGE_RELATION_STATUS_ALLY_OUTBOUND'	=> 'Requested',
	'CLANMANAGE_RELATION_STATUS_ALLY_INBOUND'	=> 'Pending',
	'CLANMANAGE_RELATION_STATUS_WAR_MUTUAL_OUTBOUND'	=> 'Active (declared by you)',
	'CLANMANAGE_RELATION_STATUS_WAR_MUTUAL_INBOUND'	=> 'Active (declared by other)',
	'CLANMANAGE_RELATION_STATUS_WAR_OUTBOUND'	=> 'Treaty Requested (by you)',
	'CLANMANAGE_RELATION_STATUS_WAR_INBOUND'	=> 'Treaty Requested (by other)',

	'CLANMANAGE_ALLY_STOP_SUBMIT'	=> 'Terminate Alliance',
	'CLANMANAGE_ALLY_STOP_CONFIRM'	=> 'Yes, end this alliance!',
	'CLANMANAGE_ALLY_CANCEL_SUBMIT'	=> 'Cancel Request',
	'CLANMANAGE_ALLY_ACCEPT_SUBMIT'	=> 'Accept Request',
	'CLANMANAGE_ALLY_DENY_SUBMIT'	=> 'Decline Request',
	'CLANMANAGE_ALLY_REQUEST_LABEL'	=> 'Request Alliance with',
	'CLANMANAGE_ALLY_REQUEST_SUBMIT'	=> 'Send Request',

	'CLANMANAGE_WAR_REQUEST_SUBMIT'	=> 'Propose Treaty',
	'CLANMANAGE_WAR_REQUEST_CONFIRM'	=> 'Yes, request to end this war!',
	'CLANMANAGE_WAR_RESUME_SUBMIT'	=> 'Retract Treaty',
	'CLANMANAGE_WAR_STOP_SUBMIT'	=> 'Accept Treaty',
	'CLANMANAGE_WAR_RESTART_SUBMIT'	=> 'Reject Treaty',
	'CLANMANAGE_WAR_RESTART_CONFIRM'	=> 'Yes, continue this war!',
	'CLANMANAGE_WAR_DECLARE_LABEL'	=> 'Declare War on',
	'CLANMANAGE_WAR_DECLARE_SUBMIT'	=> 'Send Declaration',

	'CLANMANAGE_RELATION_WARNING'	=> 'The leaders of these clans will be notified of the actions you take here!<br />Once you take action on a relation, you must wait %1$s hours before you will be allowed to change it again!',
	'CLANMANAGE_RELATION_REMOVE'	=> 'Remove?',
	'CLANMANAGE_PASSWORD_LABEL'	=> 'Change 클랜 Password',
	'CLANMANAGE_PASSWORD_SUBMIT'	=> 'Change Password',
	'CLANMANAGE_TITLE_LABEL'	=> 'Change 클랜 Title',
	'CLANMANAGE_TITLE_SUBMIT'	=> 'Change Title',
	'CLANMANAGE_LOGO_LABEL'		=> 'Change 클랜 Logo URL',
	'CLANMANAGE_LOGO_SUBMIT'	=> 'Change Logo',
	'CLANMANAGE_URL_LABEL'		=> 'Change 클랜 Homepage URL',
	'CLANMANAGE_URL_SUBMIT'		=> 'Change URL',

	// pages/clanstats
	'CLANSTATS_TITLE'		=> '클랜 통계',
	'CLANSTATS_HEADER'		=> '클랜 등수 (최소 %1$s개 회원)',
	'CLANSTATS_NO_CLANS'		=> '클랜이 만들어지지 않았습니다!',
	'CLANSTATS_TOO_SMALL'		=> '%1$s/%2$s (%3$s)개의 클랜은 이 목록에 올라올 인원이 안됩니다.',
	'CLANSTATS_INDEPENDENT'		=> '%1$s/%2$s (%3$s)개의 제국은 독립적입니다.',

	// pages/contacts
	'CONTACTS_TITLE'		=> '클랜 연락처',
	'CONTACTS_HEADER'		=> '만약 여러분이 클랜에 가입하고 싶거나, 동맹을 맺거나, 평화조약을 채결하고싶다면 여기서 원하는 사람을 찾으세요.',
	'CONTACTS_EMP_NONE'		=> '(없음)',

	// pages/credits
	'CREDITS_TITLE'			=> '만든 사람들',
	'CREDITS_HEADER'		=> 'QM Promisance 제작자',

	// pages/delete
	'DELETE_TITLE'			=> '제국 삭제',
	'DELETE_MUST_VALIDATE'		=> '인증 코드를 입력하기 전 까지는 제국을 삭제할 수 없습니다!',
	'DELETE_NEED_VALCODE'		=> '인증 코드가 필요합니다!',
	'DELETE_BAD_VALCODE'		=> '잘못된 인증 코드를 입력하였습니다!',
	'DELETE_COMPLETE'		=> '이제 당신의 제국은 지워진것으로 기록되었습니다. 참여해주셔서 감사합니다!',
	'DELETE_WAIT'			=> '새 제국을 만들기 위해서 %1$s 기다려주세요.',
	'DELETE_LOGOUT'			=> '로그아웃',
	'DELETE_HEADER'			=> '당신이 제국을 삭제하려면, 가입할 때 사용한 인증 코드를 한번 더 입력해야됩니다.',
	'DELETE_SUBMIT'			=> '제국 삭제',

	// pages/demolish
	'DEMOLISH_TITLE'		=> '철거',
	'DEMOLISH_TOO_MANY'		=> '당신이 가지고 있는 건축물보다 더 많이 철거할 수 없습니다!',
	'DEMOLISH_NOT_ENOUGH_TURNS'	=> '그렇게 많은 건축물을 철거하기에는 턴이 부족합니다!',
	'DEMOLISH_COMPLETE'		=> '%1$s턴 동안 %2$s을(를) 철거하고 그 과정에서 %3$s을(를) 벌었습니다.',
	'DEMOLISH_DROP_TOO_MUCH'	=> '그렇게 많은 토지를 버릴 수 없습니다!',
	'DEMOLISH_DROP_COMPLETE'	=> '%1$s 동안 %2$s을(를) 버렸습니다.',
	'DEMOLISH_HEADER'		=> '모든 건축물들은 철거될 때 마다 한 평의 땅과 %1$s의 비용을 돌려줍니다.<br />매 턴 마다 %2$s개의 건축물을 철거할 수 있습니다.<br />우리의 자원으로는 최대 <span class="cbad">%3$s</span>개의 건축물을 철거할 수 있습니다.<br />',
	'DEMOLISH_SUBMIT'		=> '철거 시작',
	'DEMOLISH_DROP_HEADER'		=> '최대 <span class="cbad">%1$s</span>평의 쓰지 않는 땅을 버릴 수 있으며, 매 턴 마다 %2$s평 씩 버릴 수 있습니다.<br />',
	'DEMOLISH_DROP_SUBMIT'		=> '땅 버리기',
	'DEMOLISH_LINK_BUILD'		=> '건설하기',

	// pages/farm
	'FARM_TITLE'			=> '집중 경작',
	'FARM_NOT_ENOUGH_TURNS'		=> '그렇게 많은 턴 동안 농사를 지을 수 없습니다!(턴 부족)',
	'FARM_SPECIFY_TURNS'		=> '정확하게 농사를 지을 턴을 입력해주세요.',
	'FARM_COMPLETE'			=> '%3$s턴 동안 총 %1$s개의 %2$s을(를) 수확하였습니다.',
	'FARM_HEADER'			=> '집중 경작을 하는 매 턴 마다 %1$s의 %2$s 생산량이 25%% 늘어납니다',
	'FARM_LABEL'			=> '얼만큼의 턴 동안 집중 경작을 하시겠습니까?',
	'FARM_SUBMIT'			=> '농사 시작',

	// pages/graveyard
	'GRAVEYARD_TITLE'		=> '무덤',
	'GRAVEYARD_HEADER'		=> '화생공연대기에서 수 많은 고난을 버티지 못하고 쓰러진 자들, 여기에 묻히다.',
	'GRAVEYARD_LABEL_ABANDONED'	=> '버려짐',
	'GRAVEYARD_LABEL_SUICIDED'	=> '자살',
	'GRAVEYARD_LABEL_KILLED_NOCLAN'	=> '%1$s에 의해 멸망',
	'GRAVEYARD_LABEL_KILLED_CLAN'	=> '%2$s 클랜의 %1$s에 의해 멸망',

	// pages/guide
	'GUIDE_TITLE'			=> '게임 설명',

	// pages/history
	'HISTORY_INDEX_TITLE'		=> '역사 - 처음',
	'HISTORY_INDEX_EMPTY'		=> '아직 이 게임에는 역사가 없습니다.',
	'HISTORY_ERROR_NO_DATA'		=> '그 판에는 기록이 없습니다.No history has been recorded for that round!',
	'HISTORY_ERROR_NO_CLAN'		=> 'This round did not make use of clans.',
	'HISTORY_ERROR_BAD_MODE'	=> 'Invalid mode selected!',
	'HISTORY_SUMMARY_TITLE'		=> 'History - Summary',
	'HISTORY_SUMMARY_DATES'		=> '%1$s - %2$s',
	'HISTORY_EMPIRE_TITLE'		=> 'History - 제국',
	'HISTORY_EMPIRE_HEADER'		=> 'Top Scores Listing',
	'HISTORY_EMPIRE_CREATED'	=> '제국 Created:',
	'HISTORY_EMPIRE_ALIVE'		=> 'Survivors:',
	'HISTORY_EMPIRE_DEAD'		=> 'Casualties or Neglected:',
	'HISTORY_CLAN_TITLE'		=> 'History - 클랜들',
	'HISTORY_CLAN_HEADER'		=> '클랜 Rankings (%1$s Member Minimum)',
	'HISTORY_CLAN_NO_CLANS'		=> 'There were no significant clans at the end of this round!',
	'HISTORY_CLAN_TOO_SMALL'	=> '%1$s/%2$s (%3$s) clans didn\'t have enough members to make this list.',
	'HISTORY_CLAN_INDEPENDENT'	=> '%1$s/%2$s (%3$s) empires were <a href="%4$s">independent</a>.',
	'HISTORY_MEMBER_TITLE'		=> 'History - 클랜 Members',
	'HISTORY_MEMBER_HEADER_CLAN'	=> '클랜 Member Listing',
	'HISTORY_MEMBER_HEADER_NOCLAN'	=> 'Unclanned 제국 Listing',

	// pages/land
	'LAND_TITLE'			=> '탐색하기',
	'LAND_NOT_ENOUGH_TURNS'		=> '턴이 부족하여 그렇게 많은 시간동안 탐색 활동을 할 수 없습니다!',
	'LAND_SPECIFY_TURNS'		=> '탐색 활동을 할 턴을 정확하게 숫자로 입력해주세요.',
	'LAND_COMPLETE'			=> '당신의 제국은 %2$s 동안 %1$s 만큼 넓어졌습니다.',
	'LAND_HEADER'			=> '탐색 활동을 하는 동안 매 턴 마다 최대 %1$s을 얻을 수 있습니다..',
	'LAND_LABEL'			=> '탐색 활동을 몇 턴 동안 하시겠습니까?',
	'LAND_SUBMIT'			=> '탐색 시작',

	// pages/login
	'LOGIN_TITLE'			=> '로그인',
	'LOGIN_USER_NOT_FOUND'		=> '사용자 이름을 찾을 수 없습니다. 제대로 입력하였는지 확인하세요!',
	'LOGIN_VERSION'			=> 'QM v%1$s',
	'LOGIN_COUNTER'			=> '활동화된 제국 : %1$s',
	'LOGIN_SUBMIT'			=> '로그인',
	'LOGIN_SIGNUP'			=> '- 제국 만들기 -',
	'LOGIN_TOPEMPIRES'		=> '- 최고의 제국 목록 -',
	'LOGIN_TOPCLANS'		=> '- 최고의 연합 목록 -',
	'LOGIN_TOPPLAYERS'		=> '- 최고의 플레이어들 -',
	'LOGIN_HISTORY'			=> '- 기록들 -',

	// pages/lottery
	'LOTTERY_TITLE'			=> '복권',
	'LOTTERY_UNAVAILABLE_START'	=> '이번 판이 시작하기 전에는 복권을 살 수 없습니다.',
	'LOTTERY_UNAVAILABLE_END'	=> '이번 판이 끝난 다음에는 복권을 살 수 없습니다.',
	'LOTTERY_TOO_MANY_TICKETS'	=> '오늘은 더 이상 살 수 없습니다.',
	'LOTTERY_NOT_ENOUGH_MONEY'	=> '복권을 구입할 돈이 부족합니다.',
	'LOTTERY_COMPLETE'		=> '티켓 %1$s 구입에 %2$s 사용하였습니다.',
	'LOTTERY_DESC'			=> '복권을 구입하는 것도 돈을 버는 방법 중 하나입니다.<br />복권 판매 수익은 1등 당첨금에 올라가서 1등이 당첨되기 전 까지 당첨금은 계속 올라갑니다.<br />매일 12:00pm UTC에 번호를 하나 추첨합니다. 만약 당첨자가 나타난다면 구입자에게 1등 상금을 수여하게 됩니다.',
	'LOTTERY_NEXTTICKET'		=> '복권이 하나의 번호 당 %1$s입니다.',
	'LOTTERY_MAXALLOWED'		=> '매일 최대 %1$s 까지 구입할 수 있습니다.',
	'LOTTERY_CURJACKPOT'		=> '현재 당첨금:',
	'LOTTERY_TOTALBOUGHT'		=> '다음 추첨을 위해 구입한 복권의 수 :',
	'LOTTERY_LAST_WINNER'		=> '마지막 당첨 번호는 %1$s이고, %2$s의 손에 상금 %3$s이 돌아갔습니다!',
	'LOTTERY_LAST_NOWINNER'		=> '마지막 당첨 번호는 %1$s이지만 아무도 당첨되지 않아서 당첨금에 %2$s 추가되었습니다.',
	'LOTTERY_TICKET_LISTSEP'	=> ', ',
	'LOTTERY_HAVE_TICKETS'		=> '현재 구입한 복권 번호입니다: %1$s',
	'LOTTERY_HAVE_NO_TICKETS'	=> '현재 구입한 복권은 없습니다.',
	'LOTTERY_CANT_AFFORD'		=> '당신의 제국이 지금 복권을 살 수 있는 상태인지 확인해보세요.',
	'LOTTERY_SUBMIT'		=> '복권 구입',

	// pages/magic
	'MAGIC_TITLE'			=> 'Magic Center',
	'MAGIC_UNAVAILABLE_START'	=> 'Magic spells cannot be cast 이번 판이 시작하기 전에 할 수 없습니다.',
	'MAGIC_UNAVAILABLE_END'		=> 'Magic spells cannot be cast 이번 판이 끝난 후에 할 수 없습니다.',
	'MAGIC_SELF_ILLEGAL'		=> 'You cannot cast that spell on yourself!',
	'MAGIC_SELF_INVALID'		=> 'You cannot cast that spell on yourself right now!',
	'MAGIC_SELF_INVALID_AGAIN'	=> 'You cannot cast that spell on yourself again!',
	'MAGIC_NEED_RUNES'		=> 'You do not have enough %1$s to cast that spell!',
	'MAGIC_NEED_RUNES_AGAIN'	=> 'You do not have enough %1$s to cast that spell again!',
	'MAGIC_NEED_TURNS'		=> 'You do not have enough turns to cast that spell!',
	'MAGIC_NEED_TURNS_AGAIN'	=> 'You do not have enough turns to cast that spell again!',
	'MAGIC_NEED_HEALTH'		=> 'Your %1$s are too weak to cast any spells!',
	'MAGIC_NEED_HEALTH_AGAIN'	=> 'Your %1$s are too weak to cast any more spells!',
	'MAGIC_BEGIN'			=> 'Your %1$s begin to concentrate...',
	'MAGIC_TROUBLE_ABORT'		=> 'Faced with such a crisis, your %1$s lose their concentration and fail to cast the spell.',
	'MAGIC_SELF_COMPLETE'		=> 'Finished casting spell.',
	'MAGIC_SELF_COMPLETE_AGAIN'	=> 'Finished casting spells.',

	'MAGIC_FRIEND_DISABLED'		=> 'Casting spells on friendly empires is not enabled in this game.',
	'MAGIC_FRIEND_UNAVAILABLE_PROTECT'	=> 'Magic spells cannot be cast on others 보호 받는 동안 할 수 없습니다.',
	'MAGIC_FRIEND_UNAVAILABLE_ADMIN'	=> 'Magic spells cannot be cast on others 관리자 권한에 의해서',
	'MAGIC_FRIEND_ILLEGAL'		=> 'You cannot cast that spell on another empire!',
	'MAGIC_FRIEND_INVALID'		=> 'You cannot cast that spell on that empire!',
	'MAGIC_FRIEND_DEAD'		=> 'That empire has already been destroyed - no amount of aid could possibly help it.',
	'MAGIC_FRIEND_DELETED'		=> 'That empire has already been deleted - there would be nobody to receive your gift.',
	'MAGIC_FRIEND_NEED_GATE'	=> 'You cannot cast spells on an empire in a different era unless either of you have a Time Gate open!',
	'MAGIC_FRIEND_ADMIN'		=> 'You cannot cast spells on Administrators!',
	'MAGIC_FRIEND_DISABLED'		=> 'That empire has been locked by Administration for further investigation - you may not cast spells on it.',
	'MAGIC_FRIEND_PROTECTED'	=> 'You cannot cast spells on an empire still under new player protection!',
	'MAGIC_FRIEND_VACATION'		=> 'You cannot cast spells on an empire under vacation protection!',
	'MAGIC_FRIEND_REFUSE_WAR'	=> 'Your Generals laugh at the very idea of casting such a spell on a sworn enemy.',
	'MAGIC_FRIEND_REFUSE_SIZE'	=> 'Such a powerful empire would have no need for your help.',
	'MAGIC_FRIEND_NEED_CREDITS'	=> 'You cannot cast any more spells on friendly empires right now. Wait at least an hour, then try again.',
	'MAGIC_FRIEND_COMPLETE'		=> 'Finished casting spell.',

	'MAGIC_ENEMY_UNAVAILABLE_PROTECT'	=> '보호 받는 동안 적에게 마법을 사용할 수 없습니다.',
	'MAGIC_ENEMY_UNAVAILABLE_ADMIN'	=> '관리자는 다른 나라에게 마법을 공격할 수 없습니다.',
	'MAGIC_ENEMY_ILLEGAL'		=> '다른 제국에 그 마법을 사용할 수 없습니다!',
	'MAGIC_ENEMY_INVALID'		=> '그 마법을 그 제국에 사용할 수 없습니다!',
	'MAGIC_ENEMY_DEAD'		=> 'That empire has already been destroyed - there is no point in casting spells on it.',
	'MAGIC_ENEMY_DELETED'		=> 'That empire has already been deleted.',
	'MAGIC_ENEMY_NEED_GATE'		=> 'You cannot cast spells on an empire in a different era unless either of you have a Time Gate open!',
	'MAGIC_ENEMY_ADMIN'		=> 'You cannot cast spells on Administrators!',
	'MAGIC_ENEMY_DISABLED'		=> 'That empire has been locked by Administration for further investigation - you may not cast spells on it.',
	'MAGIC_ENEMY_PROTECTED'		=> 'You cannot cast spells on an empire still under new player protection!',
	'MAGIC_ENEMY_VACATION'		=> 'You cannot cast spells on an empire under vacation protection!',
	'MAGIC_ENEMY_REFUSE_CLAN'	=> 'You cannot cast spells on an empire in your own clan.',
	'MAGIC_ENEMY_REFUSE_ALLY'	=> 'Your clan has a standing alliance with that empire - you would be a fool to violate it.',
	'MAGIC_ENEMY_REFUSE_SMALL'	=> 'Your %1$s politely refuse your orders to target a defenseless empire.',
	'MAGIC_ENEMY_REFUSE_LARGE'	=> 'Your %1$s flatly refuse your orders to target such a strong opponent.',
	'MAGIC_ENEMY_ATTACK_LIMIT'	=> 'Your %1$s are weary from casting so many spells on other empires. Let them rest for at least %2$s, then try again.',
	'MAGIC_ENEMY_DESERT_SMALL'	=> 'Your %1$s are shamed by your attack on such a weak opponent. Many desert!',
	'MAGIC_ENEMY_DESERT_LARGE'	=> 'Your %1$s tremble at the thought of retaliation from such a strong opponent. Many desert!',
	'MAGIC_ENEMY_COMPLETE'		=> 'Finished casting spell.',

	'MAGIC_SELF_LABEL'		=> '자신에게 마법 %1$s 번 사용',
	'MAGIC_SPELL_SELECT'		=> '주문을 선택하세요...',
	'MAGIC_SPELL_LABEL'		=> '%1$s (%2$s %3$s, %4$s)',
	'MAGIC_SPELL_LABEL_VARY'	=> '%1$s (varies, press Cast to confirm)',
	'MAGIC_SELF_SUBMIT'		=> '마법 실행',
	'MAGIC_FRIEND_LABEL'		=> 'Cast a Spell on 제국 %1$s',
	'MAGIC_FRIEND_SUBMIT'		=> '마법 실행',
	'MAGIC_FRIEND_VERIFY_LABEL'	=> '%1$s 제국에 발휘할 마법의 비용을 확인하세요.',
	'MAGIC_ENEMY_LABEL'		=> '%1$s 제국에 마법 공격',
	'MAGIC_ENEMY_SUBMIT'		=> '마법 실행',
	'MAGIC_ENEMY_VERIFY_LABEL'	=> '%1$s 제국에 발휘할 마법의 비용을 확인하세요.',

	// pages/main
	'MAIN_TITLE'			=> '메인',
	'MAIN_SETUSER_BAD_EMPIRE'	=> '정상적인 제국을 선택하세요!',
	'MAIN_SETUSER_COMPLETE'		=> '<strong>%1$s</strong>으로 제국이 바뀌었습니다.',
	'MAIN_RENAME_NEED_NAME'		=> '새로운 제국의 이름을 입력하세요.',
	'MAIN_RENAME_PERMISSION'	=> '이름을 바꿀 권한이 없습니다.',
	'MAIN_RENAME_COMPLETE'		=> '당신의 제국의 이름이 <strong>%1$s</strong>으로 바뀌었습니다.',
	'MAIN_SELECT_EMPIRE'		=> '제국 선택하기:',
	'MAIN_SETUSER_SUBMIT'		=> '제국 바꾸기',
	'MAIN_RENAME_SUBMIT'		=> '제국 이름 바꾸기',
	'MAIN_MODERATOR_REPORTS'	=> '%1$s개의 새로운 부정 보고가 있습니다.',
	'MAIN_UNDER_PROTECTION'		=> '%1$s 턴 동안 초보자 보호 기간입니다.',
	'MAIN_TURN_RATE'		=> '매 %2$s 마다 %1$s이 생깁니다.',
	'MAIN_TURNS_STOPPED'		=> '턴이 현재 멈추어져있습니다.',
	'MAIN_TURNS_NEXT'		=> '%2$s 후에 %1$s을 받게됩니다.',
	'MAIN_HAVE_MESSAGES'		=> '%1$s와 %2$s가 있습니다.',
	'MAIN_NO_MESSAGES'		=> '쪽지 보내기',
	'MAIN_NO_ARCHIVED_NEWS'		=> '새 소식 없음',
	'MAIN_MARK_NEWS_READ'		=> '읽은것으로 표시',
	'MAIN_NO_NEWS'			=> '새 기록 없음',
	'MAIN_VIEW_NEWS_ARCHIVE'	=> '최근 일주일간 새 소식 보기',

	// pages/manage
	'MANAGE_TITLE'			=> '제국 관리',
	'MANAGE_POLYMORPH_UNAVAILABLE'	=> '지금은 할 수 없습니다.',
	'MANAGE_POLYMORPH_NEED_RACE'	=> '변형할 종족을 선택하세요!',
	'MANAGE_POLYMORPH_BAD_RACE'	=> '정상적인 종족을 선택하세요!',
	'MANAGE_POLYMORPH_SAME_RACE'	=> '다른 종족을 선택하세요!',
	'MANAGE_POLYMORPH_FREE'		=> '종족이 바뀌었습니다.',
	'MANAGE_POLYMORPH_NEED_CONFIRM'	=> '확인란에 체크해주세요.',
	'MANAGE_POLYMORPH_NEED_TURNS'	=> '턴이 부족합니다!',
	'MANAGE_POLYMORPH_NEED_HEALTH'	=> '변형하기에는 너무 허약합니다!',
	'MANAGE_POLYMORPH_NEED_TRPWIZ'	=> '%1$s의 부족함이 느껴지십니까?',
	'MANAGE_POLYMORPH_BEGIN'	=> ' %1$s들이 집중을하고, 시민들이 하나 둘 바뀌기 시작합니다...',
	'MANAGE_POLYMORPH_UNITS_LOST'	=> '%1$s %2$s, %3$s %4$s, %5$s %6$s, %7$s %8$s, %9$s %10$s, 그리고 %11$s %12$s가 생태계 충격으로 죽었습니다.',
	'MANAGE_POLYMORPH_OTHER_LOST'	=> '%1$s 구조물, %2$s %3$s, %4$s %5$s, 그리고 %6$s들이 혼돈속에서 사라졌습니다.',
	'MANAGE_POLYMORPH_COMPLETE'	=> '이제 %1$s이(가) 되었습니다.',
	'MANAGE_TAX_NEED_RATE'		=> '정확한 세율을 입력해주세요!',
	'MANAGE_TAX_TOO_LOW'		=> '세금이 너무 낮습니다!',
	'MANAGE_TAX_TOO_HIGH'		=> '세금이 너무 높습니다!',
	'MANAGE_TAX_COMPLETE'		=> '세율이 변경되었습니다!',
	'MANAGE_INDUSTRY_TOO_HIGH'	=> '자원을 100% 이상 사용할 수 없습니다!',
	'MANAGE_INDUSTRY_COMPLETE'	=> '산업 자원 비율이 정상적으로 바뀌었습니다!',
	'MANAGE_VACATION_DISABLED'	=> '지금은 휴가를 갈 수 없습니다.',
	'MANAGE_VACATION_NEED_CONFIRM'	=> '휴가를 떠나기 위해서는 확인란을 선택해야됩니다.',
	'MANAGE_VACATION_NEED_VALIDATE'	=> '계정이 인증되기 전 까지 .',
	'MANAGE_VACATION_TOO_LATE'	=> '휴가를 떠나기에는 너무 늦었습니다!',
	'MANAGE_VACATION_COMPLETE'	=> '이제 휴가를 떠나서 당신의 계정은 잠겨있습니다. 당신의 제국은 약 %1$s 시간 이후부터 보호받습니다.',
	'MANAGE_UNVACATION_NOT_NEEDED'	=> '아직 휴가를 떠나지도 않았습니다!',
	'MANAGE_UNVACATION_NOT_YET'	=> '아직 휴가에서 돌아올 수 없습니다!',
	'MANAGE_UNVACATION_COMPLETE'	=> '당신은 휴가에서 돌아왔습니다.',
	'MANAGE_STYLE_ERROR'		=> '스타일을 선택하세요!',
	'MANAGE_STYLE_COMPLETE'		=> '테마가 변경되었습니다..',
	'MANAGE_PASSWORD_COMPLETE'	=> '비밀번호가 변경되었습니다.',
	'MANAGE_TIMEZONE_COMPLETE'	=> '시간대가 변경되었습니다.',
	'MANAGE_LANGUAGE_INVALID'	=> '현재 게임에서 지원하지 않는 언어입니다!',
	'MANAGE_LANGUAGE_COMPLETE'	=> '언어를 정상적으로 바꾸었습니다.',
	'MANAGE_HEADER_EMPIRE'		=> '제국 설정',
	'MANAGE_POLYMORPH_LABEL'	=> '변형',
	'MANAGE_POLYMORPH_REQUIREMENT'	=> '%1$s 턴과 <br />%2$s %3$s, 그리고<br />최소한 75%%의 건강',
	'MANAGE_POLYMORPH_NOPENALTY'	=> '자유롭게 가능<br />(아직 턴을 사용하지 않음)',
	'MANAGE_POLYMORPH_CONFIRM'	=> '예, 저는 변형을<br />정말 원합니다!',
	'MANAGE_POLYMORPH_SUBMIT'	=> '변형 시작',
	'MANAGE_TAX_LABEL'		=> '세율:',
	'MANAGE_TAX_SUBMIT'		=> '세율 적용',
	'MANAGE_INDUSTRY_LABEL'		=> '병력 설정',
	'MANAGE_INDUSTRY_SUBMIT'	=> '병력 적용',
	'MANAGE_VACATION_LABEL'		=> '휴가',
	'MANAGE_VACATION_EXPLAIN'	=> '휴가를 가면 일단 최소 %1$s 시간을 쉬게됩니다.<br />떠나는 순간 계정은 잠기게 되며, 당신의 제국은 %2$s 시간이 지난 이후로 보호받게 됩니다.<br />해당 판이 끝날 때가 되면, 제국은 %1$s 시간이 지난 다음 자동으로 휴가에서 복귀하게 됩니다.',
	'MANAGE_VACATION_CONFIRM'	=> '예, 정말 휴가를 떠나겠습니다!',
	'MANAGE_VACATION_SUBMIT'	=> '휴가 떠나기',
	'MANAGE_HEADER_ACCOUNT'		=> '계정 설정',
	'MANAGE_STYLE_LABEL'		=> '테마',
	'MANAGE_STYLE_SUBMIT'		=> '스타일 바꾸기',
	'MANAGE_PASSWORD_LABEL'		=> '비밀번호 변경',
	'MANAGE_PASSWORD_SUBMIT'	=> '비밀번호 바꾸기',
	'MANAGE_TIMEZONE_LABEL'		=> '시간대:',
	'MANAGE_TIMEZONE_SAMPLE'	=> '예시:',
	'MANAGE_TIMEZONE_SUBMIT'	=> '시간대 바꾸기',
	'MANAGE_LANGUAGE_LABEL'		=> '언어',
	'MANAGE_LANGUAGE_SUBMIT'	=> '언어 바꾸기',

	// pages/messages
	'MESSAGES_TITLE'		=> '편지함',
	'MESSAGES_NOCREDITS'		=> '남은 메시지를 다 썼습니다. 잠시후에 다시 보내세요.',
	'MESSAGES_NO_SUCH_EMPIRE'	=> '메시지를 받을 제국이 없습니다!',
	'MESSAGES_SUBJECT_TOO_LONG'	=> '메시지 제목이 너무 깁니다!',
	'MESSAGES_SUBJECT_INVALID'	=> '사용할 수 없는 메시지 제목입니다!',
	'MESSAGES_BODY_TOO_LONG'	=> '메시지 내용이 너무 깁니다. 내용을 조금 더 줄이세요.',
	'MESSAGES_BODY_INVALID'		=> '사용할 수 없는 메시지 내용입니다!',
	'MESSAGES_REASON_TOO_LONG'	=> '신고 사유가 너무 깁니다. 조금 더 줄이세요!',
	'MESSAGES_REASON_INVALID'	=> '사용할 수 없는 내용이 신고 사유에 포함되어있습니다!',
	'MESSAGES_SEND_COMPLETE'	=> '%1$s 제국으로 메시지를 보냈습니다.',

	'MESSAGES_REPLY_NOT_EXIST'	=> '존재하지 않는 메시지에 답장을 보낼 수 없습니다!',
	'MESSAGES_REPLY_NOT_YOURS'	=> '당신이 보내지 않은 메시지에 답변을 할 수 없습니다!',
	'MESSAGES_REPLY_NOT_SELF'	=> '당신에게 답장을 보낼 수 없습니다.',
	'MESSAGES_REPLY_ALREADY'	=> '이미 해당 메시지에 답장을 보냈습니다!',
	'MESSAGES_REPLY_DELETED'	=> '이미 해당 메시지를 지웠습니다!',
	'MESSAGES_REPLY_EMPIRE_DEAD'	=> '메시지 받는 제국은 이제 존재하지 않습니다.',
	'MESSAGES_REPLY_COMPLETE'	=> '%1$s 제국에 답장을 보냈습니다.',

	'MESSAGES_REPORT_NOT_EXIST'	=> '신고할 정확한 메시지를 선택하세요!',
	'MESSAGES_REPORT_NOT_YOURS'	=> '그 메시지는 당신것이 아닙니다.',
	'MESSAGES_REPORT_NOT_SELF'	=> '당신의 메시지를 신고할 수 없습니다.',
	'MESSAGES_REPORT_ALREADY'	=> '그 메시지는 이미 신고되었습니다.',
	// Only used with default language
	'MESSAGES_REPORT_SUBJ_LONG'	=> 'Message %1$s (from %2$s at %3$s)',
	// Only used with default language
	'MESSAGES_REPORT_SUBJ_SHORT'	=> 'Message %1$s (from empire %2$s at %3$s)',
	'MESSAGES_REPORT_COMPLETE'	=> '메시지가 신고되었습니다.',

	'MESSAGES_DELETE_COMPLETE'	=> '메시지가 삭제되었습니다.',
	'MESSAGES_DELETE_FAILED'	=> '지울 메시지가 없습니다!',

	'MESSAGES_HEADER_INBOX'		=> '받은 편지함',
	'MESSAGES_HEADER_SENT'		=> '보낸 편지함',
	'MESSAGES_READ_NOT_FOUND'	=> '그런 메시지가 없습니다!',
	'MESSAGES_READ_IN_RESPONSE'	=> 'In response to %1$sthis message%2$s...',
	'MESSAGES_LABEL_MODERATOR'	=> 'Moderator 편지함',
	'MESSAGES_SUBMIT_QUOTE'		=> '인용',
	'MESSAGES_SUBMIT_REPORT'	=> '신고',
	'MESSAGES_SUBMIT_DELETE'	=> '삭제',
	'MESSAGES_REPORT_HEADER'	=> '당신이 이 메시지를 신고하는 이유를 상세하게 써주세요:',
	'MESSAGES_REPORT_WARNING'	=> '신고 기능을 악용하게되면 메시지 기능을 사용할 수 없습니다.',
	'MESSAGES_SUBMIT_SEND_REPORT'	=> '신고하기',
	'MESSAGES_REPLY_HEADER'		=> '답장 보내기:',
	// Only used with default language
	'MESSAGES_REPLY_PREFIX'		=> 'Re: ',
	'MESSAGES_SUBMIT_SEND_REPLY'	=> '보내기',

	'MESSAGES_COLUMN_SUBJECT'	=> '제목',
	'MESSAGES_COLUMN_OUTBOX'	=> '받는 사람',
	'MESSAGES_COLUMN_INBOX'		=> '보내는 사람',
	'MESSAGES_COLUMN_DATE'		=> '날짜',
	'MESSAGES_LABEL_NO_SUBJECT'	=> '(제목 없음)',
	'MESSAGES_NONE_RECEIVED'	=> '받은 메시지가 없습니다.',
	'MESSAGES_NONE_SENT'		=> '보낸 메시지가 없습니다.',
	'MESSAGES_LABEL_SEND'		=> '%1$s 제국에 메시지 보내기',
	'MESSAGES_SUBMIT_SEND_NEW'	=> '보내기',
	'MESSAGES_CREDITS_REMAINING'	=> '현재 %1$s개의 메시지를 보낼 수 있습니다.',

	// pages/military
	'MILITARY_TITLE'		=> '전쟁처',
	'MILITARY_UNAVAILABLE_START'	=> '이번 판이 시작하기 전에 전쟁을 할 수 없습니다.',
	'MILITARY_UNAVAILABLE_END'	=> '이번 판이 끝난 후에 전쟁을 할 수 없습니다.',
	'MILITARY_UNAVAILABLE_PROTECT'	=> '보호 받는 동안 전쟁을 할 수 없습니다.',
	'MILITARY_UNAVAILABLE_ADMIN'	=> '관리자는 전쟁을 할 수 없습니다.',
	'MILITARY_TYPE_STANDARD'	=> '일반 공격',
	'MILITARY_TYPE_SURPRISE'	=> '급습',
	'MILITARY_TYPE_ARM'		=> '게릴라성 전투',
	'MILITARY_TYPE_LND'		=> '공성 모드',
	'MILITARY_TYPE_FLY'		=> '공중 폭격',
	'MILITARY_TYPE_SEA'		=> '해안 침투',
	'MILITARY_BEGIN'		=> '당신의 병력을 보냅니다...',
	'MILITARY_TIMEGATE_SELF'	=> '당신의 반짝이는 시간의 문이 병력을 다른 시대로 보냅니다...',
	'MILITARY_TIMEGATE_OTHER'	=> '다른 시간의 문이 반짝이면서 병력을 다른 시대로 보내줍니다...',
	'MILITARY_ALLY_DEFENSE'		=> '당신의 병력이 움직이자, 적국이 클랜원들에게 요청한 병력이 %1$s에서 도착했습니다...',
	'MILITARY_UNITLOSS_ROW'		=> '%1$s %2$s',
	'MILITARY_SUCCESS_HEADER'	=> '%1$s의 방어선을 뚫고 땅 %2$s평을 점령했습니다!',
	'MILITARY_SUCCESS_DESTROYED'	=> '공격하면서 %1$s을(를) 파괴하였습니다.',
	'MILITARY_SUCCESS_LOSSES'	=> '치열한 전투 끝에 %1$s을(를) 잃었습니다.',
	'MILITARY_FAILURE_HEADER'	=> '최후의 혈전 끝에 %1$s의 방어막에 가로막혔습니다.',
	'MILITARY_FAILURE_DESTROYED'	=> '혼란 가운데서도 %1$s을(를) 파괴하였습니다.',
	'MILITARY_FAILURE_LOSSES'	=> '전투중에 %1$s을(를) 잃었습니다.',
	'MILITARY_STRUCTURES_GAINED'	=> '%1$s을(를) 함께 획득하였습니다!',
	'MILITARY_STRUCTURES_DESTROYED'	=> '빼앗지 못한 땅에서도 %1$s을(를) 파괴하였습니다!',
	'MILITARY_SUCCESS_KILLED'	=> '<b>%1$s</b>이(가) 멸망하였습니다!',
	'MILITARY_SUCCESS_KILLED_LATE'	=> '<b>%1$s</b>에 더이상 땅이 없습니다.',

	'MILITARY_INVALID'		=> '잘못된 공격 방법입니다!',
	'MILITARY_NEED_TURNS'		=> '공격할 턴이 부족합니다!',
	'MILITARY_NEED_HEALTH'		=> '공격을 가기에 병력이 너무 허약합니다!',
	'MILITARY_DEAD'			=> 'That empire has already been destroyed - sending forth your army would be a waste of time.',
	'MILITARY_DELETED'		=> 'That empire has already been deleted.',
	'MILITARY_NEED_GATE'		=> 'You cannot attack an empire in a different era unless either of you have a Time Gate open!',
	'MILITARY_ADMIN'		=> 'You cannot attack Administrators!',
	'MILITARY_DISABLED'		=> 'That empire has been locked by Administration for further investigation - you may not attack it.',
	'MILITARY_PROTECTED'		=> 'You cannot attack an empire still under new player protection!',
	'MILITARY_VACATION'		=> 'You cannot attack an empire under vacation protection!',
	'MILITARY_REFUSE_CLAN'		=> 'You cannot attack an empire in your own clan.',
	'MILITARY_REFUSE_ALLY'		=> 'Your clan has a standing alliance with that empire - you would be a fool to violate it.',
	'MILITARY_REFUSE_SMALL'		=> 'Your Generals politely refuse your orders to target a defenseless empire.',
	'MILITARY_REFUSE_LARGE'		=> 'Your Generals flatly refuse your orders to target such a strong opponent.',
	'MILITARY_NEED_UNITS'		=> 'You must send at least one military unit in order to attack!',
	'MILITARY_ATTACK_LIMIT'		=> 'Your army is weary from launching so many attacks. Let them rest for at least %1$s, then try again.',
	'MILITARY_DESERT_SMALL'		=> 'Your military is shamed by your attack on such a weak opponent. Many desert!',
	'MILITARY_DESERT_LARGE'		=> 'Your military trembles at the thought of retaliation from such a strong opponent. Many desert!',
	'MILITARY_TROUBLE_ABORT'	=> 'Faced with such a crisis, your army is forced to abort their attack.',
	'MILITARY_HEADER'		=> '당신의 병력을 %1$s 제국으로 보냅니다.',
	'MILITARY_ATTACKTYPE_LABEL'	=> '공격 방식:',
	'MILITARY_SENDALL'		=> '모두 보내기',
	'MILITARY_SUBMIT'		=> '공격',

	// pages/news
	'NEWS_TITLE'			=> '소식 찾기',
	'NEWS_INVALID_DATA'		=> '잘못된 검색어 입니다!',
	'NEWS_INVALID_TYPE'		=> '잘못된 검색 방법입니다!',
	'NEWS_CLAN'			=> '클랜: %1$s',
	'NEWS_EVENT_KILLED'		=> '멸망',
	'NEWS_EVENT_TOOK_ACRES'		=> '%1$s 평',
	'NEWS_EVENT_DEFENDED'		=> '방어',
	'NEWS_EVENT_SPELL_SUCCESS'	=> '성공',
	'NEWS_EVENT_SPELL_SHIELDED'	=> '쉴드로 막음',
	'NEWS_EVENT_SPELL_FAILED'	=> '실패',
	'NEWS_EVENT_AID'		=> '외부 원조',
	'NEWS_EVENT_UNKNOWN'		=> '알려지지 않은 사건',
	'NEWS_LABEL_SEARCHBY'		=> '검색 방법:',
	'NEWS_LABEL_ATTACKER'		=> '공격',
	'NEWS_LABEL_DEFENDER'		=> '수비',
	'NEWS_LABEL_EITHER'		=> '상관 없음',
	'NEWS_LABEL_EMPIRE'		=> '제국 ID:',
	'NEWS_LABEL_CLAN'		=> '클랜:',
	'NEWS_SUBMIT'			=> '소식 찾기',
	'NEWS_EVENT_MATCH'			=> '%1$s개의 소식을 찾았습니다.',
	'NEWS_LABEL_DATE_TIME'		=>	'날짜/시간',
	'NEWS_LABEL_ATTACKER'		=>	'공격자',
	'NEWS_LABEL_EVENT'			=>	'사건',
	'NEWS_LABEL_DEFENDER'		=>	'방어자',
	

	// pages/playerstats
	'PLAYERSTATS_TITLE'		=> '플레이어 통계',
	'PLAYERSTATS_NO_SUCH_USER'	=> '이 게임에는 그런 플레이어가 없습니다!',
	'PLAYERSTATS_IS_ADMIN'		=> '%1$s은(는) 관리자입니다.',
	'PLAYERSTATS_IS_MOD'		=> '%1$s은(는) Moderator입니다.',
	'PLAYERSTATS_NO_PLAYS'		=> '%1$s just started playing on this server on %2$s and has not yet earned a reputation here.',
	'PLAYERSTATS_PLAY_SUMMARY'	=> '%1$s first started playing on this server on %2$s and has participated in %3$s round(s), not including the current round.',
	'PLAYERSTATS_PLAY_ACTIONS'	=> 'Throughout this time, this player has killed %1$s other empire(s) and has been killed %2$s time(s), launching a total of %3$s attacks (with a %4$s success rate) and being the target of %5$s attacks from others (of which %6$s were successfully held off).',
	'PLAYERSTATS_PLAY_RANKS'	=> 'This player\'s best earned ranking (relative to others) was %1$s, with an average ranking of %2$s.',
	'PLAYERSTATS_NO_HISTORY'	=> 'Unfortunately, this player has yet to survive to the end of a round to be recorded in history.',
	'PLAYERSTATS_HISTORY_HEADER'	=> 'This player survived to be remembered in the history of the following round(s):',
	'PLAYERSTATS_HISTORY_LABEL'	=> '%1$s: %2$s - %3$s',

	// pages/pubmarketbuy
	'PUBMARKET_LINK_BUY'		=> '물품 구입',
	'PUBMARKET_LINK_SELL'		=> '물품 판매',

	'PUBMARKETBUY_TITLE'			=> '열린 시장 - 구입',
	'PUBMARKETBUY_UNAVAILABLE_START'	=> '이 판이 시작하기 전에 열린 시장에 갈 수 없습니다.',
	'PUBMARKETBUY_UNAVAILABLE_END'		=> '이 판이 끝나고 열린 시장에 갈 수 없습니다.',
	'PUBMARKETBUY_UNAVAILABLE_PROTECT'	=> '보호받고 있는 동안에는 열린 시장에 갈 수 없습니다.',
	'PUBMARKETBUY_UNAVAILABLE_ADMIN'	=> '관리자에 의해서 열린 시장에 갈 수 없습니다.',
	'PUBMARKETBUY_IMPOSSIBLE_LOCKED'	=> '당신은 이미 다른 물건을 구입하는 중입니다.',
	'PUBMARKETBUY_NOT_ENOUGH_MONEY'		=> '당신은 %1$s개나 구입할 수 있는 돈이 없습니다.!',
	'PUBMARKETBUY_CHEAPER_ARRIVED'		=> '당신이 돌아다니는동안, 더 저렴한 %1$s가 시장에 도착했습니다!',
	'PUBMARKETBUY_BOUGHT_LINE'		=> '%1$s %2$s for %3$s each',
	'PUBMARKETBUY_BOUGHT_SINGLE'		=> '당신은 %1$s (총 %2$s)을 구입하였습니다..',
	'PUBMARKETBUY_BOUGHT_MULTIPLE'		=> '당신은 %1$s (총 %2$s %3$s for %4$s)를 구입하였습니다.',
	'PUBMARKETBUY_BOUGHT_NOT_ALL'		=> '아쉽지만, 남은 %1$s 들을 당신이 원하는 %2$s 만큼 구입하지 못했습니다..',
	'PUBMARKETBUY_BOUGHT_NONE'		=> '%1$s개의 %2$s를 구입하지 못했습니다.',
	'PUBMARKETBUY_SUBMIT'			=> '물품 구입',

	// pages/pubmarketsell
	'PUBMARKETSELL_TITLE'			=> '열린 시장 - 판매',
	'PUBMARKETSELL_UNAVAILABLE_START'	=> '이 판이 시작하기 전에 열린 시장에 갈 수 없습니다.',
	'PUBMARKETSELL_UNAVAILABLE_END'		=> '이 판이 끝나고 열린 시장에 갈 수 없습니다.',
	'PUBMARKETSELL_UNAVAILABLE_PROTECT'	=> '보호받고 있는 동안에는 열린 시장에 갈 수 없습니다.',
	'PUBMARKETSELL_UNAVAILABLE_ADMIN'	=> '관리자에 의해서 열린 시장에 갈 수 없습니다.',
	'PUBMARKETSELL_TOO_MANY_UNITS'		=> '%1$s개 이상의 %2$s을(를) 팔 수 없습니다!',
	'PUBMARKETSELL_TOO_FEW_UNITS'		=> '최소한 %1$s개의 %2$s을(를) 팔아야됩니다!',
	'PUBMARKETSELL_PRICE_TOO_LOW'		=> '%2$s 밑으로 %1$s을(를) 팔 수 없습니다!',
	'PUBMARKETSELL_PROCE_TOO_HIGH'		=> '%2$s 보다 비싸게 %1$s을(를) 팔 수 없습니다!',
	'PUBMARKETSELL_CANNOT_REMOVE'		=> '시장에서 물건을 회수할 수 없습니다. 이미 다른사람이 구입하려고 하고있거나 당신의 것이 아닙니다.',
	'PUBMARKETSELL_REMOVE_COMPLETE'		=> 'You have removed %1$s %2$s from the market. %3$s were returned to you.',
	'PUBMARKETSELL_REMOVE_TOO_SOON'		=> 'You cannot remove those items from the market yet.',
	'PUBMARKETSELL_SALES_HEADER'		=> 'On the market (or on the way), we have:',
	'PUBMARKETSELL_SALES_ONSALE'		=> 'On Sale, %1$s hour(s)',
	'PUBMARKETSELL_SALES_REMOVE'		=> '[제거]',
	'PUBMARKETSELL_SALES_INTRANSIT'		=> 'In Transit, %1$s hour(s) remaining',
	'PUBMARKETSELL_SALES_DELAY'		=> 'It will take %1$s hour(s) for your goods to reach the market.',
	'PUBMARKETSELL_SUBMIT'			=> '물품 판매',

	// pages/pvtmarketbuy
	'PVTMARKET_LINK_BUY'		=> '물품 구입',
	'PVTMARKET_LINK_SELL'		=> '물품 판매',

	'PVTMARKETBUY_TITLE'			=> '암시장 - 구입',
	'PVTMARKETBUY_UNAVAILABLE_START'	=> '이번 판이 시작하기 전에 암시장에 올 수 없습니다.',
	'PVTMARKETBUY_UNAVAILABLE_END'		=> '이번 판이 끝난 후에 암시장에 올 수 없습니다.',
	'PVTMARKETBUY_NOT_ENOUGH_UNITS'		=> '구입할 %1$s이(가) 부족합니다!',
	'PVTMARKETBUY_NOT_ENOUGH_MONEY'		=> '%1$s을(를) 구입할 비용이 부족합니다!',
	'PVTMARKETBUY_COMPLETE'			=> '%3$s에 %1$s개의 %2$s을(를) 구입하였습니다.',
	'PVTMARKETBUY_SUBMIT'			=> '구입',

	// pages/pvtmarketsell
	'PVTMARKETSELL_TITLE'			=> '암시장 - 판매',
	'PVTMARKETSELL_UNAVAILABLE_START'	=> '이번 판이 시작하기 전에 암시장에 올 수 없습니다.',
	'PVTMARKETSELL_UNAVAILABLE_END'		=> '이번 판이 끝난 후에 암시장에 올 수 없습니다.',
	'PVTMARKETSELL_TOO_MANY_UNITS'		=> '한번에 그렇게 많은 %1$s을(를) 판매할 수 없습니다!',
	'PVTMARKETSELL_NOT_ENOUGH_UNITS'	=> '판매할 %1$s이(가) 부족합니다!',
	'PVTMARKETSELL_COMPLETE'		=> '%3$s에 %1$s개의 %2$s을(를) 판매하였습니다..',
	'PVTMARKETSELL_SUBMIT'			=> '판매',

	// pages/revalidate
	'REVALIDATE_TITLE'		=> '인증 코드 다시 받기',
	'REVALIDATE_SUCCESS'		=> '인증 코드를 다시 보냈습니다.!',
	'REVALIDATE_ERROR'		=> '인증 메일을 보내는 도중에 오류가 발생했습니다. 관리자에게 문의해주세요. (에러 번호 %1$s)',
	'REVALIDATE_LINK_MAIN'		=> '메인 메뉴로 돌아가기',
	'REVALIDATE_HEADER'		=> '여러분의 인증 코드를 다시 받을 수 있습니다.',
	'REVALIDATE_SUBMIT'		=> '인증 코드 받기',

	// pages/scores (shared with topempires)
	'SCORES_TITLE'			=> '점수',
	'SCORES_HEADER'			=> '점수 목록',

	// pages/search
	'SEARCH_TITLE'			=> '제국 검색',
	'SEARCH_INVALID_RACE'		=> '정확한 종족을 선택해주세요!',
	'SEARCH_INVALID_ERA'		=> '정확한 세대를 선택해주세요!',
	'SEARCH_NO_RESULTS'		=> '해당하는 제국은 없습니다.',
	'SEARCH_COMPLETE'		=> '%1$s개의 제국을 찾았습니다.',
	'SEARCH_LABEL_NUM'		=> '제국 ID:',
	'SEARCH_LABEL_NAME'		=> '제국 이름:',
	'SEARCH_LABEL_CLAN'		=> '소속 클랜:',
	'SEARCH_LABEL_CLAN_ANY'		=> '모든 클랜',
	'SEARCH_LABEL_CLAN_NONE'	=> '없음 - 비연합 제국',
	'SEARCH_LABEL_CLAN_FORMAT'	=> '%1$s - %2$s',
	'SEARCH_LABEL_RACE'		=> '종족:',
	'SEARCH_LABEL_RACE_ANY'		=> '모든 종족',
	'SEARCH_LABEL_ERA'		=> '시대:',
	'SEARCH_LABEL_ERA_ANY'		=> '모든 시대',
	'SEARCH_LABEL_NETWORTH_MIN'	=> '최소 총 가치:',
	'SEARCH_LABEL_NETWORTH_MAX'	=> '최대 총 가치:',
	'SEARCH_LABEL_OFFLINE'		=> '접속중이 아닌 제국은 제외',
	'SEARCH_LABEL_DEAD'		=> '멸망한 제국은 제외',
	'SEARCH_LABEL_SORT'		=> '정렬:',
	'SEARCH_LABEL_SORT_NETWORTH'	=> '총 가치',
	'SEARCH_LABEL_SORT_LAND'	=> '땅',
	'SEARCH_LABEL_SORT_NAME'	=> '제국 이름',
	'SEARCH_LABEL_SORT_NUM'		=> '제국 ID',
	'SEARCH_LABEL_SORT_CLAN'	=> '클랜 소속',
	'SEARCH_LABEL_SORT_SCORE'	=> '점수',
	'SEARCH_LABEL_SORT_RACE'	=> '종족',
	'SEARCH_LABEL_SORT_ERA'		=> '시대',
	'SEARCH_SUBMIT'			=> '검색',

	// pages/signup
	'SIGNUP_TITLE'			=> '가입',
	'SIGNUP_ACCOUNT_DISABLED'	=> '이 계정은 사용이 중지되었습니다. 이 계정으로는 제국을 만들 수 없습니다.',
	'SIGNUP_EMAIL_BANNED'		=> '이 E-Mail 주소는 아래와 같은 이유로 사용이 금지되어있습니다: "%1$s"',
	'SIGNUP_NEED_RACE'		=> '종족을 선택하세요!',
	'SIGNUP_RACE_INVALID'		=> '올바른 종족을 선택하세요!',
	'SIGNUP_NO_MORE_EMPIRES'	=> '더 이상 제국을 만들 수 없습니다!',
	'SIGNUP_COMPLETE'		=> '<b>%1$s</b>님!, Promisance 세계로 오신것을 환영합니다.',
	'SIGNUP_MULTIPLE'		=> '당신의 제국들을 메인 화면의 목록에서 선택할 수 있습니다..',
	'SIGNUP_CONTINUE'		=> '계속 하기...',
	'SIGNUP_MAILERROR'		=> '가입 메일을 보내는 도중 오류가 발생하였습니다. 관리자에게 문의해주세요. (%1$s)',
	'SIGNUP_HEADER'			=> '<i>Promisance</i>: 가입 양식',
	'SIGNUP_WELCOME_FIRST'		=> '%1$s에 오신것을 환영합니다! 당신의 제국을 건설하기에 앞서서 아래 가입 양식을 작성해주세요!',
	'SIGNUP_WELCOME_BACK'		=> '%1$s에 돌아오신것을 환영합니다! 로그인 하기에 앞서서 당신의 제국을 만들어주세요.',
	'SIGNUP_WARN_RULES'		=> '규칙에 맞지 않는 계정은 관리자에 의해서 임의로 삭제될 수 있습니다.',
	'SIGNUP_HEADER_RULES'		=> '서버 규정',
	'SIGNUP_HEADER_MULTIS'		=> '다수 계정',
	'SIGNUP_RULES_MULTIS'		=> '플레이어는 한번에 하나의 계정만 사용할 수 있으며, 한번에 %1$s을 운영할 수 있습니다.<br />'.
						'플레이어는 자신의 계정만 사용할 수 있으며, 계정을 공유하거나 대신 키워주어서는 안됩니다.<br />'.
						'다수의 계정을 사용하는 플레이어는 해당 제국은 금지되고, 계정이 정지될 수 도 있습니다.<br />'.
						'만약 당신의 행동이 규정 위반인지 확실하지 않다면, 중재자나 관리자에게 문의하세요.',
	'SIGNUP_MULTIS_SINGLE'		=> '<b>%s</b>개의 제국',
	'SIGNUP_MULTIS_PLURAL'		=> '최대 <b>%s</b> 개의 제국들',
	'SIGNUP_HEADER_USE'		=> '사용 가능한 내용들',
	'SIGNUP_RULES_USE'		=> '<ul class="al"><li>외설적이거나 다른 플레이어들에게 공격적으로 받아드려질 수 있는 욕설은 사용할 수 없습니다.</li>'.
						'<li>불법 소프트웨어나 불법적인 행동에 대한 토론은 금지되어있습니다.</li>'.
						'<li>게임내의 돈거래는 금지되어있습니다. 사이트의 운영자를 제외하면 누구도 광고를 게시할 수 없습니다.</li>'.
						'<li>생명에 대한 위헙 (예, 현피)나 개인의 사생활을 침해하는것은 금지되어있습니다.</li></ul>'.
						'이를 위반하는 사용자의 제국이나 계정은 정지되며, 심한 경우는 IP가 정지될 수 있습니다.',
	'SIGNUP_HEADER_SUPPORT'		=> '지원',
	'SIGNUP_RULES_SUPPORT'		=> '만약 여러분이 게임을 진행하다가 문제가 발생한다면 관리자에게 문의하세요. 문의할 때는 <strong>아래의 내용을 모두 포함</strong>하여야 됩니다:'.
						'<ol class="al"><li>메시지의 제목에는 현재 문제가 발생한 게임의 이름(%1$s)을 써주세요.</li>'.
						'<li>당신의 계정 이름을 써주세요. <b>절대로</b> 비밀번호를 입력하지 마세요.</li>'.
						'<li>점수판에 나타나는 당신의 제국의 이름과 번호(ID)를 써주세요.</li>'.
						'<li>당신에게 나타나는 문제를 상세하고 알기 쉽게 써주세요.</li></ol>'.
						'<strong>이상의 내용들이 모두</strong>포함되지 않은 메시지는 관리자가 처리하지 못할 수 있습니다.',
	'SIGNUP_HEADER_EXTRA'		=> '추가 정보',
	'SIGNUP_VALIDATION_REMINDER'	=> '<i>인증 코드</i>는 당신의 E-Mail로 보내집니다. 정확한 E-Mail 주소를 입력해주세요.',
	'SIGNUP_REPLAY_REMINDER'	=> '만역 여러분이 이전에 이곳에서 같은 게임을 했다면, 해당 계정을 계속 사용할 수 있습니다. <br />아이디와 비밀번호를 입력하시고, "*" 표시된 곳만 입력해주세요.',
	'SIGNUP_ACCOUNT_INFO'		=> '계정 정보',
	'SIGNUP_PRIVACY'		=> '당신의 별명은 다른 사람들에게 공개됩니다.<br />하지만 이메일 주소는 안전하게 보관됩니다.',
	'SIGNUP_EMPIRE_INFO'		=> '제국 정보',
	'SIGNUP_RACE_DETAILS'		=> '[자세한 정보]',
	'SIGNUP_SUBMIT'			=> '가입하기',

	// pages/status
	'STATUS_TITLE'			=> '제국 상황',
	'STATUS_EMPIRE_HEADER'		=> '제국',
	'STATUS_FOOD_HEADER'		=> '농사',
	'STATUS_FOOD_PRODUCE'		=> '추정 생산량',
	'STATUS_FOOD_CONSUME'		=> '추정 소비량',
	'STATUS_FOOD_NET'		=> '총 합',
	'STATUS_FOREIGN_HEADER'		=> '대외 관계',
	'STATUS_FOREIGN_CLAN'		=> '클랜 회원 수',
	'STATUS_FOREIGN_ALLIES'		=> '동맹국',
	'STATUS_FOREIGN_WARS'		=> '적국',
	'STATUS_FOREIGN_OFFENSE'	=> '공격',
	'STATUS_FOREIGN_DEFENSE'	=> '방어',
	'STATUS_FOREIGN_KILLS'		=> '승리 회수',
	'STATUS_LAND_HEADER'		=> '토지',
	'STATUS_LAND_UNUSED'		=> '쓰지 않는 땅',
	'STATUS_CASH_HEADER'		=> '경제',
	'STATUS_CASH_INCOME'		=> '추정 수입',
	'STATUS_CASH_EXPENSE'		=> '추정 지출',
	'STATUS_CASH_NET'		=> '총 합',
	'STATUS_CASH_LOANPAY'		=> '대출 이자',
	'STATUS_CASH_PERCAP'		=> '시민당 수입',
	'STATUS_CASH_SAVINGS'		=> '저축금',
	'STATUS_CASH_LOAN'		=> '대출금',
	'STATUS_MILITARY_HEADER'	=> '군사',
	'STATUS_MILITARY_OFFPOWER'	=> '공격력',
	'STATUS_MILITARY_DEFPOWER'	=> '방어력',

	// pages/topclans (shared with clanstats)
	'TOPCLANS_TITLE'		=> 'Top 클랜들',

	// pages/topempires
	'TOPEMPIRES_TITLE'		=> '제국 순위',
	'TOPEMPIRES_HEADER'		=> '점수 순위 목록',
	'TOPEMPIRES_ALIVE'		=> '생성된 제국:',
	'TOPEMPIRES_ONLINE'		=> '현재 로그인:',
	'TOPEMPIRES_DEAD'		=> '버려지거나 파괴된 제국:',
	'TOPEMPIRES_DISABLED'		=> '관리자에 의해 정지된 제국:',
	'TOPEMPIRES_NOTE_UPDATES'	=> '점수는 매 %1$s마다 갱신됩니다.',
	'TOPEMPIRES_NOTE_ONLINE'	=> '제국의 등수에 * 기호가 붙은 것은 현재 온라인이라는 뜻입니다.',

	// pages/topplayers
	'TOPPLAYERS_TITLE'		=> '최고 플레이어',
	'TOPPLAYERS_HEADER'		=> '최고 플레이어 목록',
	'TOPPLAYERS_CREATED'		=> '등록한 플레이어:',
	'TOPPLAYERS_DISABLED'		=> '관리자에 의해 정지된 사용자:',
	'TOPPLAYERS_NOTE_PLAYING'	=> '등수 앞에 * 마크가 있는 플레이어는 이번 판 게임에 참여중입니다.',

	// pages/validate
	'VALIDATE_TITLE'		=> '인증',
	'VALIDATE_ALREADY'		=> '이미 인증되었습니다!',
	'VALIDATE_INCORRECT'		=> '인증코드가 올바르지 않습니다!',
	'VALIDATE_COMPLETE'		=> '인증에 성공했습니다.!',
	'VALIDATE_LINK_MAIN'		=> '메인메뉴로 돌아가기',
	'VALIDATE_SUBMIT'		=> '인증',
);
?>
